{
  "hash": "f2b3bf65f113d61fc6910f92ff4f1959",
  "result": {
    "engine": "knitr",
    "markdown": "## Text as Data: Naive Bayes\n\n*Week 4, 23 September*\n\nEvery dataset used so far arrived with its features already made. The UN file had a column for income and a column for urbanization; Fearon and Laitin supplied eleven covariates measured, coded, and named by somebody else. The modeling began at the point where the measurement had finished, and the measurement itself was never our problem.\n\nThis week it is our problem. The raw material is 905 tweets, and a tweet is not a row of numbers. Before any algorithm can be applied, somebody has to decide what a feature of a tweet even is, and that decision is not a technical preliminary to the analysis. It is a large part of the analysis, and most of what can go wrong this week goes wrong there rather than in the classifier.\n\nThe classifier itself, once we reach it, has an unusual property worth stating at the outset. It rests on an assumption about language that is not approximately true, or true under conditions, but flatly and obviously false, and it works anyway. Establishing why is the second half of the session.\n\n## What Naive Bayes is good at, and what it is not\n\n**Benefits.**\n\n- It is fast, in that fitting consists of counting rather than of optimization, and it scales to vocabularies of tens of thousands of words without difficulty.\n- It performs well with small training sets, which matters when every label has been assigned by a human being reading a document.\n- It can be inspected. The fitted model is a table of word frequencies, and one can read off exactly which words pushed a document in which direction.\n- It produces a probability for each document rather than a bare classification, and that probability can be thresholded to suit the purpose.\n\n**The disadvantages** are two, and they are of different kinds.\n\nThe first is that the independence assumption on which the method rests is false of language, and we will state it plainly and then violate it deliberately.\n\nThe second is subtler and matters more for political science. A text classifier is only ever as good as the labels it was trained on, and those labels were produced by a person applying a coding scheme. The model does not learn what immigration is. It learns what one coder, working from one scheme, decided to call immigration, and it will reproduce that decision faithfully, including the parts of it that were arbitrary.\n\n## The data\n\nThe corpus consists of tweets posted by `@realDonaldTrump` in 2019, filtered and hand-labeled for whether immigration is a main subject of the tweet. It contains 905 tweets.\n\nBefore everything else, make sure the necessary packages are installed: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"tm\", \"SnowballC\", \"wordcloud\", \"e1071\",\n                   \"caret\", \"ggplot2\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tm)\nlibrary(SnowballC)\nlibrary(wordcloud)\nlibrary(caret)\nlibrary(ggplot2)\n\noptions(scipen = 999)\n\nurl <- paste0(\"https://raw.githubusercontent.com/babakrezaee/\",\n              \"AppliedAI-PoliSci/refs/heads/main/data/\",\n              \"trump_immigration_2019.csv\")\n\ntweets <- read.csv(url, stringsAsFactors = FALSE)\n\nnrow(tweets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 905\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(tweets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t905 obs. of  4 variables:\n $ id   : num  1084065832941031424 1183369132634456064 1097856727020720000 1149289425836367872 1184426268177129472 ...\n $ date : chr  \"2019-01-12 20:33\" \"2019-10-13 21:09\" \"2019-02-19 21:53\" \"2019-07-11 20:08\" ...\n $ label: chr  \"other\" \"other\" \"immigration\" \"immigration\" ...\n $ text : chr  \"....the FBI was in complete turmoil (see N.Y. Post) because of Comey’s poor leadership and the way he handled t\"| __truncated__ \"Do you remember two years ago when Iraq was going to fight the Kurds in a different part of Syria. Many people \"| __truncated__ \"The failed Fast Train project in California, where the cost overruns are becoming world record setting, is hund\"| __truncated__ \"Democrats had to quickly take down a tweet called “Kids In Cages, Inhumane Treatment at the Border,” because th\"| __truncated__ ...\n```\n\n\n:::\n:::\n\n\nThe dataset has four columns: a tweet ID, a timestamp, a label, and the text itself.\n\nThe outcome needs to be a factor, and the order of its levels is a decision we should make deliberately rather than let R make alphabetically.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntweets$label <- factor(tweets$label, levels = c(\"other\", \"immigration\"))\n\ntable(tweets$label)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      other immigration \n        538         367 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(tweets$label)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      other immigration \n      0.594       0.406 \n```\n\n\n:::\n:::\n\n\nThe majority class is `other`, at roughly 59 per cent, and that figure plays the same role here that the two per cent base rate played last week. It is the accuracy obtainable by a model that reads nothing, and no accuracy figure means anything until it has been compared against it.\n\nNotice, though, how different this baseline is from last week's. Civil war onset occurred in two country-years in a hundred, and the baseline was consequently 98 per cent, which is nearly impossible to beat and useless to match. Here the two classes are of comparable size, which makes accuracy a sensible thing to report at all. That comparability is not a fact about Trump's Twitter account. It is a property of a corpus that was deliberately constructed to have it, and the price of the construction is that the corpus no longer represents the stream of tweets it was drawn from.\n\n## Part I. From tweets to a matrix\n\n### Reading the text before modeling it\n\nThe single most useful thing to do with a new corpus is to read some of it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in 1:4) {\n  cat(as.character(tweets$label[i]), \"|\", tweets$text[i], \"\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nother | ....the FBI was in complete turmoil (see N.Y. Post) because of Comey’s poor leadership and the way he handled the Clinton mess (not to mention his usurpation of powers from the Justice Department). My firing of James Comey was a great day for America. He was a Crooked Cop...... \n\nother | Do you remember two years ago when Iraq was going to fight the Kurds in a different part of Syria. Many people wanted us to fight with the Kurds against Iraq, who we just fought for. I said no, and the Kurds left the fight, twice. Now the same thing is happening with Turkey...... \n\nimmigration | The failed Fast Train project in California, where the cost overruns are becoming world record setting, is hundreds of times more expensive than the desperately needed Wall! \n\nimmigration | Democrats had to quickly take down a tweet called “Kids In Cages, Inhumane Treatment at the Border,” because the horrible picture used was from the Obama years. Very embarrassing! @foxandfriends \n```\n\n\n:::\n:::\n\n\nFour tweets, and already several of the difficulties are visible. There are URLs, which carry no meaning of their own. There are handles beginning with `@`. There are capitals used for emphasis rather than for grammar. There are curly quotation marks rather than straight ones, which look identical on the page and are entirely different characters to R. And at least one of these tweets is labeled in a way that a reasonable person might dispute.\n\n### The bag of words\n\nThe representation we are going to use is the simplest one available, and it is worth stating what it discards before we adopt it.\n\nA document is represented as the set of words it contains, and nothing else. Word order is discarded. Grammar is discarded. Which word modifies which is discarded. \"The wall stopped the caravan\" and \"the caravan stopped the wall\" become the same document.\n\nThis is called the **bag of words**, and the name is accurate: we tip the document into a bag, shake it, and record what is inside.\n\nStated that way it sounds indefensible, and for many questions it is. For *this* question it is mostly adequate, because whether a tweet is about immigration is largely determined by which words appear in it and hardly at all by the order in which they appear. A tweet containing *border*, *caravan*, and *asylum* is about immigration under any permutation. The adequacy of the representation depends on the question, therefore, and not on the corpus, and a question about who did what to whom would require something else entirely.\n\n### Cleaning, one decision at a time\n\n`tm` works on a **corpus**, which is its container for a collection of documents.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorpus <- VCorpus(VectorSource(tweets$text))\n\ncorpus[[1]]$content\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"....the FBI was in complete turmoil (see N.Y. Post) because of Comey’s poor leadership and the way he handled the Clinton mess (not to mention his usurpation of powers from the Justice Department). My firing of James Comey was a great day for America. He was a Crooked Cop......\"\n```\n\n\n:::\n:::\n\n\nCleaning is applied with `tm_map()`, which takes a corpus and a transformation and returns a corpus. We will need one transformation that `tm` does not supply, namely the removal of a pattern, so we build it first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreplace_with_space <- content_transformer(function(x, pattern) {\n  gsub(pattern, \" \", x)\n})\n```\n:::\n\n\n`content_transformer()` wraps an ordinary function operating on character strings so that `tm_map()` will apply it to the text of each document. Any cleaning step you invent yourself will need this wrapper.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- tm_map(corpus, content_transformer(tolower))\nclean <- tm_map(clean, replace_with_space, \"http[s]?://\\\\S*\")\nclean <- tm_map(clean, replace_with_space, \"@\\\\S+\")\nclean <- tm_map(clean, replace_with_space, \"[^a-z ]\")\nclean <- tm_map(clean, removeWords, stopwords(\"english\"))\nclean <- tm_map(clean, stemDocument)\nclean <- tm_map(clean, stripWhitespace)\n\nclean[[1]]$content\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"fbi complet turmoil see n y post comey s poor leadership way handl clinton mess mention usurp power justic depart fire jame comey great day america crook cop\"\n```\n\n\n:::\n:::\n\n\nSeven lines, and every one of them is a substantive choice rather than a housekeeping step. Taking them in order:\n\n**Lowercasing** makes *Wall* and *wall* the same feature, which is what we want, and also makes *US* and *us* the same feature, which is not. There is no setting that gets both right.\n\n**Removing URLs and handles** is straightforward here, since a link carries no words. Note that this throws away `@ThomasHomanICE`, the acting director of Immigration and Customs Enforcement, whose presence in a tweet is close to decisive evidence about its topic. We are discarding a genuinely informative feature for the sake of a simple pipeline, and whether that is the right trade is a question you could answer empirically in the workshop.\n\n**`[^a-z ]`** deletes everything that is not a lowercase letter or a space, which removes punctuation, digits, emoji, and — the reason it is written this way rather than with `removePunctuation()` — the curly quotation marks and en dashes that `removePunctuation()` leaves untouched. Without this line the model acquires features that are invisible on screen and appear in the output as things like `<U+2019>`, which is among the more disorienting hours available to a beginner in text analysis.\n\n**Stopwords** are the words carrying little topical content: *the*, *and*, *of*, *is*. `stopwords(\"english\")` is a list somebody else compiled, and you should look at it (`head(stopwords(\"english\"), 50)`) rather than trust it. It contains *not*, which reverses meaning, and it contains *against*, which is doing real work in a corpus about policy disputes.\n\n**Stemming** reduces inflected forms to a common root, so *immigration*, *immigrants*, and *immigrate* all become `immigr`. This is why the output above is not quite English. The gain is that three sparse features become one dense one; the cost is that the stems are occasionally wrong and always ugly.\n\n**Whitespace** is cosmetic, and is the one line here that is genuinely housekeeping.\n\nThe order matters, and not always in obvious ways. We strip punctuation *before* removing stopwords, which means `don't` has already become `dont` and no longer matches the stopword `don't`. Reversing those two lines changes the vocabulary. This is the argument of Denny and Spirling [@denny2018], one of this week's readings, and their finding is worth carrying into any project of your own: preprocessing choices that are reported in a single sentence of an appendix, if at all, can change the substantive results.\n\n### The document-term matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndtm <- DocumentTermMatrix(clean)\n\ndtm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<<DocumentTermMatrix (documents: 905, terms: 2735)>>\nNon-/sparse entries: 16606/2458569\nSparsity           : 99%\nMaximal term length: 16\nWeighting          : term frequency (tf)\n```\n\n\n:::\n:::\n\n\nThis is the object the whole of Part I was building toward. Rows are documents, columns are terms, and the entry in row $i$ and column $j$ is the number of times term $j$ appears in document $i$.\n\nTwo numbers in that output deserve attention. There are close to three thousand distinct terms across 905 tweets, so the matrix has several times more columns than rows. And it is 99 per cent sparse, meaning that essentially every cell is zero, since any given tweet contains perhaps fifteen of the three thousand available words.\n\nBoth properties are normal for text and both would be alarming anywhere else. A regression with three thousand predictors and nine hundred observations cannot be fitted at all. Naive Bayes can, and the reason it can is exactly the assumption we are about to make.\n\n### What is in the corpus\n\nBefore modeling, it is worth looking at the two classes side by side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(0, 0, 2, 0))\n\nset.seed(7)\n\nwordcloud(clean[tweets$label == \"immigration\"], min.freq = 12,\n          random.order = FALSE, colors = brewer.pal(7, \"Blues\")[3:7])\ntitle(\"immigration\")\n\nwordcloud(clean[tweets$label == \"other\"], min.freq = 12,\n          random.order = FALSE, colors = brewer.pal(7, \"Oranges\")[3:7])\ntitle(\"other\")\n```\n\n::: {.cell-output-display}\n![](w04-text-as-data_files/figure-html/unnamed-chunk-9-1.png){width=1056}\n:::\n:::\n\n\nWord clouds are a poor instrument for inference, since the eye cannot compare areas reliably and the layout is random. As a first look at a corpus, however, they are hard to beat.\n\nNote what they show and what they do not. `border` and `wall` dominate the immigration cloud, as expected. But `illeg` appears in *both*, because the negative class was deliberately constructed to contain tweets about illegal wiretaps and illegal impeachments. And `democrat` is large on both sides, because Trump attacks Democrats over immigration and over everything else. The classifier cannot succeed here by finding a single keyword, which is the reason this corpus was built the way it was.\n\n### Splitting before anything else\n\nThe rows were shuffled before distribution, so splitting on row number gives an approximately random split.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(tweets)\n\ntrain_id <- 1:floor(0.8 * n)\n\ndtm_train <- dtm[train_id, ]\ndtm_test  <- dtm[-train_id, ]\n\ny_train <- tweets$label[train_id]\ny_test  <- tweets$label[-train_id]\n\nc(train = length(y_train), test = length(y_test))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntrain  test \n  724   181 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(y_train)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ny_train\n      other immigration \n      0.613       0.387 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(y_test)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ny_test\n      other immigration \n      0.519       0.481 \n```\n\n\n:::\n:::\n\n\nThe class proportions differ somewhat between the two halves, which is what a random split of nine hundred cases does, and the test-set proportion is the baseline any test-set accuracy must be compared against.\n\n**The split comes before the next step, and the order is not arbitrary.** We are about to choose which words to keep, and that choice will be made using the training data alone. Selecting a vocabulary on all 905 tweets and then splitting would let information from the test set into the model, and the resulting accuracy would be optimistic for a reason nothing in the output would reveal. This is the most common way a text classification pipeline lies to its author.\n\n### Trimming the vocabulary\n\nMost of the three thousand terms appear once or twice in the entire corpus. They cannot support any generalization, and they enlarge the model considerably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq_words <- findFreqTerms(dtm_train, 5)\n\nlength(freq_words)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 651\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(freq_words, 24)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"abl\"       \"absolut\"   \"abus\"      \"act\"       \"action\"    \"actual\"   \n [7] \"adam\"      \"administr\" \"african\"   \"agenda\"    \"agent\"     \"ago\"      \n[13] \"agre\"      \"agreement\" \"aid\"       \"alien\"     \"allow\"     \"almost\"   \n[19] \"along\"     \"alreadi\"   \"also\"      \"alway\"     \"amend\"     \"america\"  \n```\n\n\n:::\n:::\n\n\nKeeping only terms appearing at least five times in the training documents reduces the vocabulary by roughly three quarters. The threshold of five is conventional and arbitrary in equal measure, which makes it a parameter of exactly the kind we have twice now chosen by cross-validation: $k$ in Week 2, the complexity parameter in Week 3, and the size of the vocabulary here. Changing it and watching what happens is the first thing to try in the workshop.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndtm_train <- dtm_train[, freq_words]\ndtm_test  <- dtm_test[, freq_words]\n```\n:::\n\n\nThe test matrix is subset to the *training* vocabulary. Words that occur only in the test set are discarded, which is the correct behavior: a model that never saw a word during training has nothing to say about it.\n\n### The counts stay as counts\n\nThat is the matrix we will model, and no further transformation of it is needed. Rows are tweets, columns are words, and each entry is the number of times that word is used in that tweet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts_train <- as.matrix(dtm_train)\ncounts_test  <- as.matrix(dtm_test)\n\ndim(counts_train)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 724 651\n```\n\n\n:::\n\n```{.r .cell-code}\ncounts_train[1:3, 1:6]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Terms\nDocs abl absolut abus act action actual\n   1   0       0    0   0      0      0\n   2   0       0    0   0      0      0\n   3   0       0    0   0      0      0\n```\n\n\n:::\n:::\n\n\n`as.matrix()` converts `tm`'s compressed representation into an ordinary R matrix, which is easier to work with and, at this size, costs nothing. On a corpus of a hundred thousand documents it would exhaust the memory of your laptop, and the compressed form would have to be kept.\n\n### Two rates per word\n\nAlmost everything the classifier will do is contained in the following comparison, which we can compute directly and without any model at all. The question is only how often each word gets used in each kind of tweet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_immigration <- colSums(counts_train[y_train == \"immigration\", ])\ntotal_other       <- colSums(counts_train[y_train == \"other\", ])\n\ntotals <- data.frame(word        = freq_words,\n                     immigration = total_immigration,\n                     other       = total_other)\n\nhead(totals[order(-totals$immigration), 2:3], 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         immigration other\nborder           237    49\nwall             131    12\nwill             111   140\ndemocrat          90    51\nimmigr            67     5\nmexico            66    34\nsouthern          63     1\ncountri           62    38\nsecur             62    13\nilleg             54    51\ngreat             52   124\nwant              46    22\n```\n\n\n:::\n:::\n\n\nAcross the training tweets labeled `immigration`, the stem `border` is used 237 times; across those labeled `other`, 49 times.\n\nThose two numbers cannot be compared as they stand, because the two groups are not the same size and do not contain the same quantity of text.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(total_immigration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4786\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(total_other)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6395\n```\n\n\n:::\n:::\n\n\nThe immigration tweets supply fewer words in total, so *every* word will tend to show a smaller count there, whether or not it is distinctive. The remedy is to divide by the total, which turns a count into a rate: out of every thousand words used in immigration tweets, how many are this word?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_immigration <- 1000 * total_immigration / sum(total_immigration)\nrate_other       <- 1000 * total_other       / sum(total_other)\n\nrates <- data.frame(word        = freq_words,\n                    immigration = rate_immigration,\n                    other       = rate_other)\n\nround(head(rates[order(-rates$immigration), 2:3], 12), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         immigration other\nborder         49.52  7.66\nwall           27.37  1.88\nwill           23.19 21.89\ndemocrat       18.80  7.97\nimmigr         14.00  0.78\nmexico         13.79  5.32\nsouthern       13.16  0.16\ncountri        12.95  5.94\nsecur          12.95  2.03\nilleg          11.28  7.97\ngreat          10.87 19.39\nwant            9.61  3.44\n```\n\n\n:::\n:::\n\n\nRead the first row as a conditional statement: **given that** a tweet is about immigration, about 50 of every thousand words it uses are `border`; given that it is about something else, about 8 are.\n\nThat is a conditional probability, and it is the only probabilistic idea this handout requires. A conditional probability is a rate computed within a subgroup rather than across everything. We are not asking how common *border* is in the corpus. We are asking how common it is **within** the immigration tweets, and then asking the same question again within the others. Naive Bayes is built entirely out of quantities of this kind, and every one of them is a proportion you could work out by hand from `colSums()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(rates, aes(other, immigration)) +\n  geom_abline(slope = 1, intercept = 0, colour = \"gray60\", linetype = 2) +\n  geom_point(alpha = 0.4, colour = \"steelblue\") +\n  geom_text(data = subset(rates, immigration > 6 | other > 6),\n            aes(label = word), size = 3, vjust = -0.6) +\n  labs(x = \"Uses per 1,000 words in *other* tweets\",\n       y = \"Uses per 1,000 words in *immigration* tweets\")\n```\n\n::: {.cell-output-display}\n![](w04-text-as-data_files/figure-html/unnamed-chunk-17-1.png){width=768}\n:::\n:::\n\n\nThe dashed line is equality, and a word sitting on it carries no information whatever about the label. Distance from the line is informativeness, and the direction of the departure is which way the word votes.\n\nMost of the vocabulary sits in the corner near the origin, used rarely in both classes. A small number of words sit far above the line: `border`, `wall`, `southern`, `secur`, `immigr`. A few sit below it, `great`, `presid`, and `thank` among them, and they are evidence *against* the immigration label. And `will` sits high on both axes, which is to say it is common everywhere and therefore useless.\n\nNothing has been fitted. This figure is the model, drawn before we build it.\n\n## Part II. Naive Bayes\n\n### The question the model asks\n\nWe have a tweet, and we want to know which label it should receive. The tempting way to proceed is to ask directly: given these words, how likely is the tweet to be about immigration?\n\nThat question is difficult to answer, because the number of possible combinations of words is astronomically large and we have 724 training tweets. Almost no combination will ever have been observed.\n\nThe move that makes the problem tractable is to turn the question around. Instead of asking how likely the label is given the words, we ask **how likely the words are given each label**, which is a question we can answer, because it is the table of rates we just computed. Then we compare.\n\nFor a tweet containing *border* and *wall*, the comparison runs:\n\n- If this tweet were about immigration, how surprising would these words be? Not very: in immigration tweets *border* is used at about 50 words per thousand and *wall* at about 27.\n- If this tweet were about something else, how surprising would they be? Considerably more so: about 8 per thousand and about 2.\n\nThe words are far less surprising under the first supposition than the second, and the tweet is therefore assigned to `immigration`. That is the entire idea. **Bayes' rule is the formal statement of \"turn the question around,\"** and it also supplies the correction for how common each label is to begin with, so that a rare category requires more evidence than a common one. For our purposes the sentence is enough; the algebra is in the further reading for those who want it.\n\n### The naive assumption, which is false\n\nTurning the question around gets us to \"how likely are these words, given the label,\" and that is still a question about a whole combination of words at once. The final simplification, the one the method is named for, is this:\n\n> Assume that, within a class, each word appears independently of every other.\n\nWhich is to say that once we know the tweet is about immigration, learning that it contains *southern* tells us nothing about whether it contains *border*.\n\nThat is false. It is not a convenient approximation or a claim that holds under stated conditions. *Southern* and *border* co-occur constantly in this corpus, as do *illegal* and *immigration*, and *caravan* and *migrant*. Language is nothing but dependence between words.\n\nThe assumption is made anyway, because it converts an impossible calculation into a possible one: the joint question about a whole tweet becomes a product of the separate per-word rates in the table above, each of which we can estimate from a few hundred documents.\n\nThe consequence is specific and worth knowing, because it determines how the output should be read. Correlated words constitute double counting. When a tweet contains *border*, *southern*, *wall*, and *patrol*, the model treats these as four independent pieces of evidence when they are closer to one piece stated four times, and it therefore becomes far more confident than the evidence warrants. This is why naive Bayes classifies well and yet reports probabilities that pile up at 0 and 1 with almost nothing in between. **The ranking is usually right and the confidence is usually overstated**, so these numbers can be used to sort documents but should not be read as calibrated probabilities.\n\n### Words that never occurred\n\nOne arithmetic problem has to be dealt with before fitting. Consider the words that appear in one class of the training data and never in the other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnever_in_other <- names(which(total_other == 0))\n\nlength(never_in_other)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21\n```\n\n\n:::\n\n```{.r .cell-code}\nnever_in_other\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"aid\"          \"alien\"        \"apprehend\"    \"build\"        \"caravan\"     \n [6] \"census\"       \"citizenship\"  \"cross\"        \"daca\"         \"deport\"      \n[11] \"emerg\"        \"expens\"       \"humanitarian\" \"migrant\"      \"progress\"    \n[16] \"reduc\"        \"renov\"        \"schumer\"      \"section\"      \"solv\"        \n[21] \"stay\"        \n```\n\n\n:::\n:::\n\n\nTwenty-one words are used in immigration tweets and never once in an `other` tweet. Several are the terms one would expect — `caravan`, `deport`, `daca`, `migrant`, `alien`, `apprehend` — and several are not: `stay`, `progress`, `solv`, `expens` have nothing to do with immigration and are absent from the other class by accident, having been used five or six times in the whole training set and happened to land on one side.\n\nThe estimated rate for such a word in the `other` class is zero out of 6,395, and because the model multiplies the per-word rates together, a single zero drives the entire product to zero. One occurrence of `caravan` would then rule out the `other` label absolutely, no matter what the remaining thirty words in the tweet said.\n\nThat is too strong a conclusion to draw from six thousand words of training text. The absence of a word is evidence that it is rare in that class, not proof that it is impossible.\n\nThe standard repair, **Laplace smoothing**, adds one pretend occurrence of every word to every class before the rates are computed, so that no rate is exactly zero and no single word can veto a class outright.\n\n### Fitting\n\nFitting is two lines, because fitting is nothing but the counting we have already done.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_immigration <- (total_immigration + 1) / sum(total_immigration + 1)\np_other       <- (total_other + 1) / sum(total_other + 1)\n```\n:::\n\n\nEach vector holds, for one class, the share of that class's words accounted for by each word in the vocabulary. The `+ 1` is the smoothing, visible here as an actual addition rather than hidden behind an argument, and adding it to the denominator as well keeps each vector summing to one.\n\nOne thing remains, which is how common each label is to begin with. A tweet with no informative words in it should fall to whichever label is more common, and Bayes' rule supplies that correction automatically.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_immigration <- mean(y_train == \"immigration\")\nprior_other       <- mean(y_train == \"other\")\n\nround(c(other = prior_other, immigration = prior_immigration), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      other immigration \n      0.613       0.387 \n```\n\n\n:::\n:::\n\n\nThat is the whole model: two rate tables and two prior probabilities. Nothing was optimized, nothing converged, and there is no random seed to set. It can also be read directly, which is a thing that could not be said of last week's forest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(1000 * c(immigration = p_immigration[[\"border\"]],\n               other       = p_other[[\"border\"]]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nimmigration       other \n      43.77        7.10 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(1000 * c(immigration = p_immigration[[\"great\"]],\n               other       = p_other[[\"great\"]]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nimmigration       other \n       9.75       17.74 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(1000 * c(immigration = p_immigration[[\"caravan\"]],\n               other       = p_other[[\"caravan\"]]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nimmigration       other \n       2.02        0.14 \n```\n\n\n:::\n:::\n\n\nThe first word points strongly toward `immigration` and the second, `great`, points the other way. The third is one of the twenty-one: its rate in the `other` class is no longer zero, but it is very small, and a tweet mentioning caravans can still be classified as `other` if everything else about it says so.\n\n::: callout-note\nYou may be expecting a call to a modeling function here, and `e1071` does provide `naiveBayes()`. Given a matrix of numbers, however, that function assumes each feature is normally distributed within each class, which is badly wrong for word counts that are zero in nine cases out of ten; fed this matrix it classifies almost every tweet as `immigration`. The arithmetic above is the version the literature means by naive Bayes for text, and it is short enough to write out.\n:::\n\n### Predicting\n\nFor a new tweet we work out how well each of the two rate tables accounts for the words it contains, and assign it to whichever does better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore_immigration <- as.vector(counts_test %*% log(p_immigration)) +\n  log(prior_immigration)\n\nscore_other <- as.vector(counts_test %*% log(p_other)) +\n  log(prior_other)\n\npred <- factor(ifelse(score_immigration > score_other, \"immigration\", \"other\"),\n               levels = c(\"other\", \"immigration\"))\n\nhead(pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] other       other       immigration other       immigration other      \nLevels: other immigration\n```\n\n\n:::\n:::\n\n\nThe matrix multiplication does one thing per tweet: for every word in the vocabulary, take that word's rate under one label, and add it in once for each time the tweet uses it. A tweet using *border* four times therefore contributes four times the evidence of a tweet using it once, which is the whole reason for keeping counts rather than mere presence.\n\nLogarithms are used because the alternative is multiplying several hundred numbers of size one in a thousand, which underflows to zero on any computer. Adding logarithms instead leaves the ordering of the two scores unchanged, and the ordering is all we need.\n\n### The confusion matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncm <- table(Predicted = pred, Actual = y_test)\n\ncm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Actual\nPredicted     other immigration\n  other          82           5\n  immigration    12          82\n```\n\n\n:::\n\n```{.r .cell-code}\naccuracy <- sum(diag(cm)) / sum(cm)\nround(accuracy, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9061\n```\n\n\n:::\n\n```{.r .cell-code}\nbaseline <- mean(y_test == \"other\")\nround(baseline, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5193\n```\n\n\n:::\n:::\n\n\nRoughly 90 per cent correct against a baseline of roughly 52 per cent, and unlike last week the gap is large. The model has learned something.\n\nIt is worth being precise about what it is 90 per cent accurate *at*. This is a corpus assembled so that the two classes would be of comparable size; in Trump's actual 2019 output, immigration tweets are a clear minority and the tweets that are not about immigration are far more varied than the ones collected here. Run on the full year, the model would meet many more opportunities to produce a false alarm, and its performance would fall.\n\nLast week's discipline still applies, then: the summary number is not where the substance lies. The table is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfusionMatrix(pred, y_test, positive = \"immigration\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n             Reference\nPrediction    other immigration\n  other          82           5\n  immigration    12          82\n                                             \n               Accuracy : 0.9061             \n                 95% CI : (0.8539, 0.9443)   \n    No Information Rate : 0.5193             \n    P-Value [Acc > NIR] : <0.0000000000000002\n                                             \n                  Kappa : 0.8124             \n                                             \n Mcnemar's Test P-Value : 0.1456             \n                                             \n            Sensitivity : 0.9425             \n            Specificity : 0.8723             \n         Pos Pred Value : 0.8723             \n         Neg Pred Value : 0.9425             \n             Prevalence : 0.4807             \n         Detection Rate : 0.4530             \n   Detection Prevalence : 0.5193             \n      Balanced Accuracy : 0.9074             \n                                             \n       'Positive' Class : immigration        \n                                             \n```\n\n\n:::\n:::\n\n\n`caret` supplies the quantities that accuracy conceals, and three of them are worth reading now, with a fuller treatment in Week 6.\n\n**No Information Rate** is the baseline computed above, printed by `caret` so that it cannot be overlooked, together with a test of whether the model beats it.\n\n**Sensitivity**, also called recall, is the share of genuine immigration tweets that the model found. Of the immigration tweets in the test set, it caught almost all of them.\n\n**Positive predictive value**, also called precision, is the share of the tweets it flagged that really were about immigration, and here it is noticeably lower. The model over-flags: it would rather call a borderline tweet `immigration` than miss one.\n\nWhich of those two numbers matters more is not a statistical question. If the classifier is being used to estimate how much of Trump's 2019 output concerned immigration, over-flagging inflates the estimate directly and precision is the number to watch. If it is being used to retrieve a set of tweets for a human being to read through, recall matters more and a few false positives cost only reading time.\n\n### The most informative words\n\nThe fitted model is a pair of tables, so we can ask which words move it most. For each word, compare its rate in one class with its rate in the other, on a log scale so that the two directions are symmetric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_ratio <- sort(log(p_immigration / p_other))\n\ntop <- c(head(log_ratio, 12), tail(log_ratio, 12))\n\npar(mar = c(4, 7, 3, 2))\n\nbarplot(top, horiz = TRUE, las = 1, cex.names = 0.8,\n        col = ifelse(top > 0, \"steelblue\", \"darkorange\"),\n        xlab = \"log ratio, immigration versus other\",\n        main = \"The words that move the classifier\")\n```\n\n::: {.cell-output-display}\n![](w04-text-as-data_files/figure-html/unnamed-chunk-25-1.png){width=768}\n:::\n:::\n\n\nThis is the compensation for having a simple model, and it is worth comparing with last week's variable importance plot, which could report only *how much* a feature mattered. Here we can read the direction as well, and the words themselves are legible: `southern`, `apprehend`, `caravan`, `alien`, `humanitarian`, `loophol` on one side, and `impeach`, `witch`, `hunt`, `collus`, `mueller` on the other.\n\nThe orange side is worth a moment, because it shows the classifier learning something other than the concept we asked it to learn. Impeachment and the Mueller investigation are not the opposite of immigration. They are simply what else Trump was tweeting about in 2019, and the model has discovered that a tweet about the Mueller report is not about the border. That inference is correct on this corpus and would transfer to no other year, no other author, and no other period.\n\n### Reading the errors\n\nFewer than twenty test tweets were misclassified, and reading all of them is more informative than any summary statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_text <- tweets$text[-train_id]\n\nwrong <- which(pred != y_test)\n\nlength(wrong)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in wrong) {\n  cat(\"actual:\", as.character(y_test[i]),\n      \"| predicted:\", as.character(pred[i]), \"\\n\",\n      substr(test_text[i], 1, 180), \"\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nactual: other | predicted: immigration \n Everyone very excited about the new deal with Mexico! \n\nactual: immigration | predicted: other \n While the reviews and reporting on our Border Immigration Agreement with Mexico have been very good, there has nevertheless been much false reporting (surprise!) by the Fake and Co \n\nactual: other | predicted: immigration \n “This is not Congressional Oversight, this is bullying.” Jason Riley, The Wall Street Journal \n\nactual: other | predicted: immigration \n Kevin Corke, @FoxNews “Don’t forget, Michael Cohen has already been convicted of perjury and fraud, and as recently as this week, the Wall Street Journal has suggested that he may  \n\nactual: immigration | predicted: other \n Our Border Control Agents have done an incredible job under very adverse conditions. I am very proud to have increased their salaries because of the great job they do. Nobody deser \n\nactual: other | predicted: immigration \n As Corey Lewandowski stated very clearly yesterday in front of the House Judiciary Committee, President Trump didn’t do anything wrong or illegal. But they all know that. The Democ \n\nactual: other | predicted: immigration \n “Poll shows Dems losing interest in Impeachment inquiry all across the board. These Polls are actually devastating to the Democrats. But the writing was on the wall. He’s done so m \n\nactual: other | predicted: immigration \n Been fully briefed on earthquake in Southern California. All seems to be very much under control! \n\nactual: other | predicted: immigration \n Senator Cindy Hyde-Smith is doing a GREAT JOB for the people of Mississippi and fully supports our #MAGA Agenda. Cindy is tough on Crime, Strong on the Border and Illegal Immigrati \n\nactual: other | predicted: immigration \n I will be signing our 738 Billion Dollar Defense Spending Bill today. It will include 12 weeks  Paid Parental Leave, gives our troops a raise, importantly creates the SPACE FORCE,  \n\nactual: immigration | predicted: other \n Looking forward to soon being in North Carolina to hold a big rally for wonderful Dan Bishop, who is running for Congress. His opponent wants Open Borders, Sanctuary Cities, and So \n\nactual: other | predicted: immigration \n I will be there in two weeks, The Southern White House!https://twitter.com/Trump/status/1204520225607225344 … \n\nactual: immigration | predicted: other \n THANK YOU @DHSgov, @CBP, and @ICEgov! https://t.co/BzNwKoUJlg \n\nactual: other | predicted: immigration \n It was a very bad week for the Democrats, with the GREAT economic numbers, The Virginia disaster and the State of the Union address. Now, with the terrible offers being made by the \n\nactual: immigration | predicted: other \n The Fake News Media, in particular the Failing @nytimes, is writing phony and exaggerated accounts of the Border Detention Centers. First of all, people should not be entering our  \n\nactual: other | predicted: immigration \n Just talked to Governor Roy Cooper of North Carolina as Hurricane Dorian ominously comes up the East Coast. We are monitoring it at the @WhiteHouse, ready to assist via our great t \n\nactual: other | predicted: immigration \n I will be interviewed by Jeanine Pirro at 9:00 P.M. on @FoxNews. Watch @JesseBWatters before and @greggutfeld after. All terrific people. I am in the White House waiting for Cryin’ \n```\n\n\n:::\n:::\n\n\nThe failures fall into recognizable families, and none of them is random.\n\nThere are two tweets about the **Wall Street** Journal and one in which the writing was on the **wall**, and in each the model saw *wall*. There is an earthquake in **Southern** California and a reference to the **Southern** White House, in which it saw *southern*. There is a tweet insisting that the president did nothing **illegal**, in which it saw *illeg*. These are the near misses the corpus was built to contain, and they are precisely the errors the bag of words guarantees, since *Wall Street* is a phrase and a bag has no phrases in it.\n\nThere is an endorsement of Senator Cindy Hyde-Smith, who is described as tough on crime and strong on the border and illegal immigration. The coding scheme says that endorsement boilerplate is `other`, on the grounds that the border is one slot in a formula rather than the subject of the tweet, and the model, having no notion of the difference, disagrees. Here the model is not making an error about the world. It is failing to reproduce a coding rule, and the rule was a defensible decision that could have gone the other way.\n\nAnd there is a tweet thanking `@DHSgov`, `@CBP`, and `@ICEgov`, labeled `immigration`, that the model called `other` because after the third line of our cleaning pipeline there was almost nothing left of it but the words *thank you*.\n\nEach family points to a different repair: word pairs rather than single words for *Wall Street*, keeping handles for the CBP tweet, and, for the endorsement boilerplate, nothing that a bag of words can do at all.\n\n## The politics of classification\n\nEvery model this term has been an instrument for sorting cases into categories, and text classifiers are distinctive only in that the categories are usually categories of speech.\n\nConsider what this one is. It is a small machine that reads political speech and decides what it is about. Scaled up and pointed at a stream rather than a file, that is content moderation, media monitoring, and a large part of contemporary state surveillance of political communication. The architecture in this handout is the architecture of those systems, differing in scale and in vocabulary rather than in kind.\n\nTwo properties of what we built are therefore worth carrying forward.\n\nThe first is that the categories arrive from outside the model and are not discoverable from within it. Someone decided that `immigration` and `other` were the relevant distinction, and no amount of accuracy makes that the right distinction to have drawn. The choice of categories is prior to everything technical and is almost never presented as a choice.\n\nThe second is that the errors are not evenly distributed. Our classifier over-flags, and the tweets it wrongly flags are not a random selection: they are the ones using the vocabulary of immigration for other purposes. Any system of this kind misclassifies in a patterned way, and the pattern falls on whoever happens to speak in the terms the model has learned to watch for. When the stakes are a table in a paper, this is a measurement error. When the stakes are a takedown, a flag, or a visit, it is something else.\n\nWeek 2 ended on who defines similarity and Week 3 on who sets the threshold. This week the question is who writes the codebook, since by the time the model is trained, the most consequential decisions have already been made and are no longer visible anywhere in the output.\n\n## Reading\n\nGrimmer, J., and Stewart, B. M. 2013. \"Text as Data: The Promise and Pitfalls of Automatic Content Analysis Methods for Political Texts.\" *Political Analysis* 21(3): 267–297. [@grimmer2013]\n\nThe standard orientation to the field, and the source of the principles this handout has been quietly applying throughout: that all language models are wrong but some are useful, that there is no globally best method, and above all that validation is not optional. Read their discussion of supervised methods alongside Part II, and note how much of the article is about what can go wrong rather than about what to run.\n\nDenny, M. J., and Spirling, A. 2018. \"Text Preprocessing For Unsupervised Learning: Why It Matters, When It Misleads, and What To Do About It.\" *Political Analysis* 26(2): 168–189. [@denny2018]\n\nThis is the article behind the cleaning section. Their demonstration is that decisions reported in a sentence of an appendix — stemming, stopwords, whether to lowercase — can change substantive conclusions, and that the ordering of those decisions is itself consequential. Their setting is unsupervised, and the reason to read it here is that supervised work hides the same problem behind an accuracy figure that looks like validation and is not.\n\nBarberá, P., Boydstun, A. E., Linn, S., McMahon, R., and Nagler, J. 2021. \"Automated Text Classification of News Articles: A Practical Guide to Using Supervised Machine Learning Methods.\" *Political Analysis* 29(1): 19–42. [@barbera2021]\n\nThe closest article to what we did above, and the one to read for the parts this handout compressed. Give particular attention to their treatment of the human coding stage, including how many coders are needed and how disagreement between them should be handled, since that is the stage our corpus has exactly one of.\n\n**Recommended, not required.**\n\nHopkins, D. J., and King, G. 2010. \"A Method of Automated Nonparametric Content Analysis for Social Science.\" *American Journal of Political Science* 54(1): 229–247. [@hopkins2010]\n\nWorth reading for one argument that cuts against the whole framing of this week. Most political science questions about text are questions about *proportions* — what share of tweets concerned immigration — rather than about individual documents, and the authors show that a classifier optimized for per-document accuracy can produce biased estimates of exactly those proportions, because its errors need not cancel. If you intend to count categories rather than retrieve documents, this is the article to have read first.\n\n## Before the workshop\n\nInstall `tm`, `SnowballC`, `wordcloud`, `caret`, and `e1071`, and run every chunk in this handout once. Nothing here takes more than a few seconds, and the entire pipeline runs in well under a minute, which is a pleasant change from last week. `e1071` is not called directly anywhere below, but `caret` needs it installed in order to report the confusion matrix.\n\nRead the data README, at `data/trump_immigration_2019_README.md` in the course repository, and in particular the coding scheme and the four rules for hard cases. It also carries a content warning that is worth taking seriously: these tweets make disputed empirical claims about immigrants, and some of the language is ugly. They are reproduced unedited because editing them would corrupt the corpus.\n\n## Questions for the session\n\nCome with a view on at least two of these.\n\n1.  The independence assumption is false of language and the classifier works anyway. What does that suggest about the relationship between the realism of a model's assumptions and its usefulness? Is your answer the same for a predictive model as for an explanatory one?\n\n2.  Our cleaning pipeline deleted `@ThomasHomanICE`, the handle of the acting director of ICE, whose presence is close to decisive evidence about a tweet's topic. Defend the deletion. Then defend the opposite choice. Which argument would you actually make in a paper, and what would you have to report either way?\n\n3.  The model learned that `impeach`, `mueller`, and `collus` are evidence against the immigration label. That is correct on this corpus and would transfer to nothing. How would you detect this kind of learning in a model of your own, given that every diagnostic in this handout reports it as success?\n\n4.  The coding scheme decides that immigration mentioned as the seventh item in a list of accomplishments is `other`. A different coder could decide otherwise. Trace what would change: the labels, the model, the accuracy, and the substantive claim you would end up making about how much of Trump's 2019 output concerned immigration.\n\n5.  Our classifier over-flags, calling borderline tweets `immigration` rather than missing them. Name a research use where that is the right error to make, and one where it would invalidate the result.\n\n6.  This corpus was assembled so that the two classes would be roughly balanced, which is why an accuracy figure is interpretable at all. It is therefore no longer a sample of anything. What would you have to do differently if the question were not \"is this tweet about immigration\" but \"what share of Trump's 2019 tweets were about immigration\"?\n\n7.  This handout built a machine that reads political speech and decides what it is about, using roughly forty lines of R and 724 labeled examples. Given how little that took, what follows about who is able to build such systems, and about what a political scientist's distinctive contribution to them should be?\n",
    "supporting": [
      "w04-text-as-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}