{
  "hash": "4fea36dc6b4e6b1c2ca9204a332c2c72",
  "result": {
    "engine": "knitr",
    "markdown": "# Evaluating AI Systems\n\n*Week 6, 7 October*\n\nWeek 5 ended owing you an answer. A language model had classified a corpus of NATO tweets, the output had the right shape, and nothing in that session could establish whether any of it was correct, because those tweets carried no labels. Since then the same exercise has been run on material that does carry labels: the 181 tweets of the Week 4 test set, hand-coded by a human reading each one, given to a language model that was shown no labeled examples at all.\n\nIt agreed with the human coder on 95 percent of them. The Naive Bayes classifier of Week 4, trained on 724 hand-coded tweets, manages roughly 90 percent on the same cases. If those two numbers are the whole story, then Week 4 was a waste of an afternoon, and the sensible advice to anybody studying political text is to write a paragraph of English and stop there.\n\nBoth numbers are accurate. However, the conclusion does not follow from them, and the gap between what these two figures measure and what they are commonly taken to show is the subject of this session.\n\nTwo reasons are developed below, and they operate at different levels. The first concerns what an accuracy figure is a statement about, which turns out to be agreement with one coder's application of one codebook rather than correspondence with the world. The second is more specific and, for anybody intending to use these labels in a project, considerably more alarming: labels that are 95 percent correct do not yield estimates that are 95 percent correct, and the error that survives is not noise but bias.\n\n## Part I. What accuracy hides\n\n### The classifier, rebuilt\n\nEverything in this part runs on the Week 4 pipeline, compressed and otherwise unchanged. Nothing in the chunk below is new, and the commentary on any line of it is in last week but one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"tm\", \"SnowballC\", \"caret\", \"e1071\", \"ggplot2\", \"pROC\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tm)\nlibrary(SnowballC)\nlibrary(caret)\nlibrary(ggplot2)\n\nurl4 <- paste0(\"https://raw.githubusercontent.com/babakrezaee/\",\n               \"AppliedAI-PoliSci/refs/heads/main/data/\",\n               \"trump_immigration_2019.csv\")\n\ntweets <- read.csv(url4, stringsAsFactors = FALSE,\n                   colClasses = c(id = \"character\"))\ntweets$label <- factor(tweets$label, levels = c(\"other\", \"immigration\"))\n\ncorpus <- VCorpus(VectorSource(tweets$text))\n\nreplace_with_space <- content_transformer(function(x, pattern) {\n  gsub(pattern, \" \", x)\n})\n\nclean <- tm_map(corpus, content_transformer(tolower))\nclean <- tm_map(clean, replace_with_space, \"http[s]?://\\\\S*\")\nclean <- tm_map(clean, replace_with_space, \"@\\\\S+\")\nclean <- tm_map(clean, replace_with_space, \"[^a-z ]\")\nclean <- tm_map(clean, removeWords, stopwords(\"english\"))\nclean <- tm_map(clean, stemDocument)\nclean <- tm_map(clean, stripWhitespace)\n\ndtm <- DocumentTermMatrix(clean)\n\ntrain_id <- 1:floor(0.8 * nrow(tweets))\n\nfreq_words <- findFreqTerms(dtm[train_id, ], 5)\n\ncounts_train <- as.matrix(dtm[train_id, freq_words])\ncounts_test  <- as.matrix(dtm[-train_id, freq_words])\n\ny_train <- tweets$label[train_id]\ny_test  <- tweets$label[-train_id]\n\ntotal_immigration <- colSums(counts_train[y_train == \"immigration\", ])\ntotal_other       <- colSums(counts_train[y_train == \"other\", ])\n\np_immigration <- (total_immigration + 1) / sum(total_immigration + 1)\np_other       <- (total_other + 1) / sum(total_other + 1)\n\n# The two scores, exactly as in Week 4\nscore_immigration <- as.vector(counts_test %*% log(p_immigration)) +\n  log(mean(y_train == \"immigration\"))\n\nscore_other <- as.vector(counts_test %*% log(p_other)) +\n  log(mean(y_train == \"other\"))\n\n# Week 4 classified by asking which score was larger. The same comparison,\n# written as a probability that the tweet is about immigration:\nprob <- 1 / (1 + exp(-(score_immigration - score_other)))\n\nnb_pred <- factor(ifelse(prob > 0.5, \"immigration\", \"other\"),\n                  levels = c(\"other\", \"immigration\"))\n```\n:::\n\n\nOne line there is new, and the whole of this part depends on it.\n\nWeek 4 computed `score_immigration` and `score_other` and classified a tweet by asking which was larger. Those scores are sums of logarithms, so their units mean nothing outside the model and neither number can be interpreted on its own. The line that follows them converts the comparison into something that can be interpreted: $P(\\text{immigration} \\mid \\text{tweet})$, the probability the classifier assigns to a tweet being about immigration. The transformation is the logistic one, familiar from logistic regression, and it is monotone, so it changes no tweet's position relative to any other.\n\n**The classifier's default is to flag a tweet when that probability exceeds 0.5**, which is simply the rule that a tweet goes to whichever class the model thinks more likely. Asking whether the probability exceeds 0.5 and asking whether `score_immigration` exceeds `score_other` are the same question in two notations. That cut point, rather than anything in the classifier itself, is what we are about to interrogate.\n\n### Precision and recall, at last\n\nTwice now, in the Week 2 and Week 4 assignments, two numbers have been deferred with a promise that they belong here. Both describe the same confusion matrix from different directions, and both are computed with respect to a positive class that the researcher nominates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncm <- confusionMatrix(nb_pred, y_test, positive = \"immigration\")\n\ncm$table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Reference\nPrediction    other immigration\n  other          82           5\n  immigration    12          82\n```\n\n\n:::\n\n```{.r .cell-code}\nround(cm$byClass[c(\"Precision\", \"Recall\", \"F1\")], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrecision    Recall        F1 \n    0.872     0.943     0.906 \n```\n\n\n:::\n:::\n\n\nWrite the four cells of that table as TP, FP, FN, and TN, where positive means immigration, and the quantities are these:\n\n$$\n\\text{Recall} = \\text{Sensitivity} = \\frac{TP}{TP + FN}\n\\qquad\n\\text{Specificity} = \\frac{TN}{TN + FP}\n$$\n\n$$\n\\text{Precision} = \\frac{TP}{TP + FP}\n\\qquad\nF_1 = 2 \\cdot \\frac{\\text{Recall} \\times \\text{Precision}}{\\text{Recall} + \\text{Precision}}\n$$\n\nRead the denominators, because that is where the difference lives. **Recall**, also called sensitivity or the true positive rate, divides by everything that genuinely is immigration, so it answers a question about the cases that really are positive: of the tweets that concern immigration, what proportion did the classifier find? **Precision**, which `caret` also reports as positive predictive value, divides by everything the classifier flagged, so it answers a question about the model's claims: of the tweets it called immigration, what proportion really were? The first is a statement about coverage, the second about trustworthiness, and a classifier can be excellent at one while being poor at the other.\n\n**Specificity** is recall's mirror image on the other class, dividing by everything that genuinely is not immigration, and it matters most when the negative class is the one you care about protecting. **$F_1$** is the harmonic mean of precision and recall, which is a way of refusing to let a model look good by sacrificing one of them entirely.\n\n`caret` will report the pair you ask for, and the `mode` argument is worth knowing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfusionMatrix(nb_pred, y_test, positive = \"immigration\",\n                mode = \"prec_recall\")$byClass[c(\"Precision\", \"Recall\", \"F1\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrecision    Recall        F1 \n0.8723404 0.9425287 0.9060773 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfusionMatrix(nb_pred, y_test, positive = \"immigration\",\n                mode = \"sens_spec\")$byClass[c(\"Sensitivity\", \"Specificity\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSensitivity Specificity \n  0.9425287   0.8723404 \n```\n\n\n:::\n:::\n\n\nNeither, however, is a property the classifier possesses on its own: both are properties of the classifier taken together with a decision about where the line is drawn, and the next section makes that dependence visible.\n\n### The threshold is a choice, not a finding\n\nFlagging a tweet when the probability passes 0.5 is a convention rather than a result. Any other cut point produces a different classifier from the same fitted model, and nothing in the data says that one half is the right place to stand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncuts <- seq(0.1, 0.9, by = 0.1)\n\nsweep_out <- data.frame()\n\nfor (cc in cuts) {\n  pred_c <- factor(ifelse(prob > cc, \"immigration\", \"other\"),\n                   levels = c(\"other\", \"immigration\"))\n  tp <- sum(pred_c == \"immigration\" & y_test == \"immigration\")\n  fp <- sum(pred_c == \"immigration\" & y_test == \"other\")\n  fn <- sum(pred_c == \"other\" & y_test == \"immigration\")\n  tn <- sum(pred_c == \"other\" & y_test == \"other\")\n  sweep_out <- rbind(sweep_out,\n                     data.frame(threshold = cc,\n                                flagged   = tp + fp,\n                                precision = tp / (tp + fp),\n                                recall    = tp / (tp + fn),\n                                accuracy  = (tp + tn) / length(y_test)))\n}\n\nsweep_out$default <- sweep_out$threshold == 0.5\n\nround(sweep_out[, 1:5], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  threshold flagged precision recall accuracy\n1       0.1     106     0.802  0.977    0.873\n2       0.2     100     0.840  0.966    0.895\n3       0.3      99     0.848  0.966    0.901\n4       0.4      96     0.865  0.954    0.906\n5       0.5      94     0.872  0.943    0.906\n6       0.6      91     0.901  0.943    0.923\n7       0.7      90     0.900  0.931    0.917\n8       0.8      86     0.907  0.897    0.906\n9       0.9      81     0.914  0.851    0.890\n```\n\n\n:::\n:::\n\n\nRead that table one row at a time, because each row is a complete confusion matrix compressed into three numbers. At a threshold of 0.1 the classifier flags a tweet on the slightest suspicion, so it finds nearly every immigration tweet and buys that coverage with false alarms. At 0.9 it flags only what it is nearly certain about, and the tweets it flags are nearly all correct, while a good many genuine ones are let through. The row marked 0.5 is the default, and it is one row among nine rather than the answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sweep_out, aes(recall, precision)) +\n  geom_path(colour = \"steelblue\", linewidth = 1) +\n  geom_point(colour = \"grey25\", size = 1.9) +\n  geom_text(aes(label = threshold), size = 3.1, colour = \"grey25\",\n            hjust = -0.35, vjust = -0.5) +\n  geom_point(data = sweep_out[sweep_out$default, ],\n             colour = \"maroon\", size = 3.4) +\n  geom_text(data = sweep_out[sweep_out$default, ],\n            label = \"default, p = 0.5\", colour = \"maroon\",\n            size = 3.3, hjust = 1.15, vjust = 1.8) +\n  expand_limits(x = max(sweep_out$recall) + 0.04) +\n  labs(x = \"recall\", y = \"precision\",\n       title = \"Every point is the same classifier, cut in a different place\",\n       subtitle = \"Labels are the probability threshold for flagging a tweet\")\n```\n\n::: {.cell-output-display}\n![](w06-evaluation_files/figure-html/unnamed-chunk-6-1.png){width=864}\n:::\n:::\n\n\nThe curve falls from left to right, which is the trade-off drawn rather than described, and the labels say what it costs to move along it. There is nothing special about the maroon point. It is simply where a convention happens to put us, and its neighbors show what a different convention would have bought.\n\n### Why there is a trade-off at all\n\nThe curve shows that gaining one quantity costs the other, and it is worth knowing why that is inevitable rather than a quirk of this classifier.\n\nThe two measures divide by different things, and only one denominator is fixed.\n\nRecall divides by the tweets that genuinely are about immigration. In our test set that is 87 tweets, and it stays 87 no matter what the classifier does. Precision divides by the tweets the classifier flagged, and that number is entirely under its control. Lower the threshold and it flags more, so it catches more of the real ones and recall rises. However, the extra tweets it picks up are the ones it was least sure about, so more of them are wrong, and precision falls.\n\nPut plainly: **precision is for when you need to be sure, recall is for better safe than sorry.**\n\nA spam filter is the clearest case, because almost everyone has an intuition about it already. Think about which mistake you would rather it made. A spam message reaching your inbox is a nuisance, and you delete it in a second. A real message sent to the junk folder, a job offer or an exam result, may never be seen at all. The costs are wildly unequal, so a spam filter is built for **precision**: when it says spam, it had better be right, and it will let some spam through to stay that way.\n\nNow change the application and the answer flips. A screening test for a serious disease is built for **recall**. Missing a case is the expensive mistake, while a false alarm costs a second test and some worry, so the sensible design catches everything that might be a case and sorts out the false alarms later. Same mathematics, opposite setting.\n\nOur classifier sits closer to the spam filter than to the screening test, which is why the default threshold of 0.5 is not obviously the right one for every purpose.\n\n### Try it yourself\n\nDrag the threshold and watch the four cells move. Everything below is computed from the same 181 test tweets as the table above, and the table is laid out exactly as `caret` lays it out: predictions down the side, the truth across the top under the heading `Reference`.\n\n\n::: {.cell}\n\n:::\n\n\n```{ojs}\n//| echo: false\ndata = transpose(eval_data)\n```\n\n```{ojs}\n//| echo: false\nviewof t = Inputs.range([0.01, 0.99], {value: 0.5, step: 0.01,\n  label: \"Flag a tweet when the probability exceeds\"})\n```\n\n```{ojs}\n//| echo: false\ncounts = {\n  let tp = 0, fp = 0, fn = 0, tn = 0;\n  for (const d of data) {\n    const flagged = d.prob > t;\n    const positive = d.truth === \"immigration\";\n    if (flagged && positive) tp++;\n    else if (flagged && !positive) fp++;\n    else if (!flagged && positive) fn++;\n    else tn++;\n  }\n  return {tp: tp, fp: fp, fn: fn, tn: tn};\n}\n```\n\n```{ojs}\n//| echo: false\nhtml`<table style=\"border-collapse:collapse;font-size:0.95em;margin-bottom:1em\">\n  <tr>\n    <td></td>\n    <td colspan=\"2\" style=\"padding:4px 14px;text-align:center;font-style:italic;color:#555\">Reference</td>\n  </tr>\n  <tr>\n    <td style=\"padding:6px 14px;font-style:italic;color:#555\">Prediction</td>\n    <td style=\"padding:6px 14px;border-bottom:1px solid #ccc;text-align:center\">other</td>\n    <td style=\"padding:6px 14px;border-bottom:1px solid #ccc;text-align:center\">immigration</td>\n  </tr>\n  <tr>\n    <td style=\"padding:6px 14px;text-align:right\"><b>other</b></td>\n    <td style=\"padding:6px 14px;text-align:center;background:#eef3f8\"><b>${counts.tn}</b><br><span style=\"font-size:.78em;color:#666\">correct</span></td>\n    <td style=\"padding:6px 14px;text-align:center;background:#fdf0ea\"><b>${counts.fn}</b><br><span style=\"font-size:.78em;color:#666\">missed</span></td>\n  </tr>\n  <tr>\n    <td style=\"padding:6px 14px;text-align:right\"><b>immigration</b></td>\n    <td style=\"padding:6px 14px;text-align:center;background:#fdf0ea\"><b>${counts.fp}</b><br><span style=\"font-size:.78em;color:#666\">false alarm</span></td>\n    <td style=\"padding:6px 14px;text-align:center;background:#eef3f8\"><b>${counts.tp}</b><br><span style=\"font-size:.78em;color:#666\">correct</span></td>\n  </tr>\n</table>`\n```\n\n```{ojs}\n//| echo: false\nhtml`<p style=\"font-size:1.05em\">\n<b>Precision</b> ${counts.tp + counts.fp === 0 ? \"undefined\" : (counts.tp / (counts.tp + counts.fp)).toFixed(3)}\n&nbsp;&nbsp;·&nbsp;&nbsp;\n<b>Recall</b> ${(counts.tp / (counts.tp + counts.fn)).toFixed(3)}\n&nbsp;&nbsp;·&nbsp;&nbsp;\n<b>Accuracy</b> ${((counts.tp + counts.tn) / data.length).toFixed(3)}\n&nbsp;&nbsp;·&nbsp;&nbsp;\n<span style=\"color:#666\">tweets flagged ${counts.tp + counts.fp} of ${data.length}</span>\n</p>`\n```\n\n```{ojs}\n//| echo: false\ncurve = {\n  const out = [];\n  for (let c = 0.01; c <= 0.99; c += 0.01) {\n    let tp = 0, fp = 0, fn = 0;\n    for (const d of data) {\n      const f = d.prob > c, p = d.truth === \"immigration\";\n      if (f && p) tp++; else if (f && !p) fp++; else if (!f && p) fn++;\n    }\n    if (tp + fp > 0) out.push({recall: tp / (tp + fn), precision: tp / (tp + fp)});\n  }\n  return out;\n}\n```\n\n```{ojs}\n//| echo: false\nPlot.plot({\n  width: 560, height: 380, marginLeft: 55, marginBottom: 45,\n  x: {label: \"recall\", domain: [0, 1]},\n  y: {label: \"precision\", domain: [0, 1]},\n  marks: [\n    Plot.line(curve, {x: \"recall\", y: \"precision\", stroke: \"steelblue\", strokeWidth: 2}),\n    Plot.dot([{recall: counts.tp / (counts.tp + counts.fn),\n               precision: counts.tp / (counts.tp + counts.fp)}],\n             {x: \"recall\", y: \"precision\", fill: \"maroon\", r: 7})\n  ]\n})\n```\n\nDrag it to the far left and the classifier becomes paranoid, flagging nearly everything and missing almost nothing, at the cost of a great many false alarms. Drag it to the far right and it becomes cautious, flagging only what it is nearly certain of, and quietly letting real immigration tweets through. The dot never leaves the curve, because the curve is every threshold at once.\n\nWhich point on that curve is the right one is not a question the data can answer. If the labels are going to be counted, for instance to estimate what share of a year's output concerned immigration, then false alarms inflate the count directly and precision is the quantity to protect. If the labels are going to retrieve a set of documents for a person to read, missing cases is the costly error and recall matters more, since a false alarm costs only reading time. The choice is made by the purpose, and reporting the accuracy without reporting the purpose conceals it.\n\n### ROC and AUC, the same sweep in the standard form\n\nThe table above is a threshold sweep, and there is a conventional way of drawing one that you will meet in every applied paper. The **ROC curve** plots sensitivity against one minus specificity, that is, the true positive rate against the false positive rate, as the threshold moves from one to zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pROC)\n\nroc_nb <- roc(response = y_test, predictor = prob,\n              levels = c(\"other\", \"immigration\"), direction = \"<\")\n\nauc(roc_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.9711\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(roc_nb, col = \"steelblue\", lwd = 2,\n     main = paste(\"Naive Bayes, AUC =\", round(auc(roc_nb), 3)))\n```\n\n::: {.cell-output-display}\n![](w06-evaluation_files/figure-html/unnamed-chunk-15-1.png){width=576}\n:::\n:::\n\n\nThe diagonal is what a coin would achieve, since a model with no information gains a true positive for every false positive it accepts. A curve bending toward the top left is doing better than that, and the **AUC**, the area under the curve, compresses the whole picture into one number.\n\nThat number has a clean interpretation worth remembering, because it is not an accuracy. Take one immigration tweet and one other tweet at random. The AUC is the probability that the classifier gives the immigration one the higher score. It is therefore a statement about **ranking** rather than about labeling, and it does not depend on the threshold at all.\n\nThat independence is the attraction and also the trap. A model can have an excellent AUC and be useless at the threshold you actually deploy, because AUC averages over thresholds you would never choose. Report it to describe how well a model orders documents, and report precision and recall at your chosen cut point to describe what it will do in practice. Reporting only the AUC is a way of not saying what the system will actually do.\n\n::: {.callout-note}\nThere is a second curve of the same kind, the precision-recall curve, which is what we drew above. On a balanced problem the two tell much the same story. When the positive class is rare, as with civil war onset in Week 3, the ROC curve flatters a model badly, because a large number of true negatives makes the false positive rate look small however many false alarms there are. For rare outcomes, prefer the precision-recall curve.\n:::\n\n::: {.callout-note}\n**Calibration** is a third property, distinct from both of these: whether a model that says seventy percent is right about seventy percent of the time. It is the central question for anything used as an early warning system, so it belongs with next week's material on crisis management rather than here.\n:::\n\nThat is the apparatus: precision and recall, a threshold that is a decision rather than a discovery, and a curve showing what each decision costs. It was built on a classifier we fitted ourselves, which is why every part of it could be inspected.\n\nPart II turns the same apparatus on something we did not build and cannot open.\n\n## Part II. Validating a language model\n\nWeek 5 ended with an admission. A language model had classified a corpus, the output had the right shape, and nothing in that session established whether any of it was correct, because the NATO tweets carried no labels to check against. The instrument required was the one Week 4 built, and it is applied here.\n\nTwo systems are now in play, so the naming below is fixed and used consistently. **The classifier** is the Naive Bayes model of Week 4, trained on 724 hand-coded tweets. **The model**, or the language model, is the one from last week, which was trained on nothing of ours and told what to do in a paragraph of English.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl6 <- paste0(\"https://raw.githubusercontent.com/babakrezaee/\",\n               \"AppliedAI-PoliSci/refs/heads/main/data/\",\n               \"llm_labels_w6.csv\")\n\nllm <- read.csv(url6, stringsAsFactors = FALSE,\n                colClasses = c(id = \"character\"))\n\nstr(llm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t181 obs. of  7 variables:\n $ id        : chr  \"1124672389416144905\" \"1120715879640174592\" \"1106205023548133376\" \"1173803449202249728\" ...\n $ date      : chr  \"2019-05-04 21:49\" \"2019-04-23 23:47\" \"2019-03-14 22:46\" \"2019-09-17 11:38\" ...\n $ text      : chr  \"Very good call yesterday with President Putin of Russia. Tremendous potential for a good/great relationship wit\"| __truncated__ \"Great interview by Jared. Nice to have extraordinarily smart people serving our Country! https://t.co/d6Tgrn4Tzn\" \"A vote for today’s resolution by Republican Senators is a vote for Nancy Pelosi, Crime, and the Open Border Democrats!\" \"Beautiful evening in New Mexico with Great American Patriots! https://t.co/S8eDG3dAq0\" ...\n $ human     : chr  \"other\" \"other\" \"immigration\" \"other\" ...\n $ llm_main  : chr  \"other\" \"other\" \"immigration\" \"other\" ...\n $ llm_reword: chr  \"other\" \"other\" \"immigration\" \"other\" ...\n $ llm_model2: chr  \"other\" \"other\" \"immigration\" \"other\" ...\n```\n\n\n:::\n:::\n\n\n### What is in the file, and where it came from\n\nThe file carries four labels for every tweet, and the rest of this part is built on the differences between them, so it is worth being precise about what each one is.\n\n| Column | What produced it |\n|---|---|\n| `human` | The Week 4 hand coding, one person working from a written codebook |\n| `llm_main` | A language model, given the prompt below, called **prompt A** |\n| `llm_reword` | The **same model** on the same tweets, given a differently worded prompt saying the same thing, called **prompt B** |\n| `llm_model2` | A **different model** from the same provider, given prompt A again |\n\nSo two things vary, and only one at a time. Comparing `llm_main` against `llm_reword` holds the model fixed and changes the wording. Comparing `llm_main` against `llm_model2` holds the wording fixed and changes the model. The exact model names and the date of the run are recorded in `data/llm_labels_w6_README.md`, since a measurement of this kind is meaningless without them.\n\nA word on what \"a different model\" means here, because the vocabulary is looser than it looks. Both models come from the same provider and the same family, trained in the same way on much the same material, and they differ in **scale**: the number of parameters and the quantity of computation behind each answer. Providers rarely publish those numbers, so the practical signals available to you are the price per token and whatever tier name the provider has given it. The one used for `llm_model2` is the more expensive of the two. That matters for how much the comparison is worth, and the point is taken up at the end of this part: two models from one company are not two independent opinions.\n\nBoth prompts were written to do the same job, and neither is a straw man.\n\n**Prompt A**, which produced `llm_main` and `llm_model2`:\n\n> You are coding tweets for a political science project.\n>\n> Decide whether immigration is a main subject of the tweet. This includes the southern border, the border wall, illegal immigration, deportation, ICE, sanctuary cities, asylum, visas, and DACA.\n>\n> If immigration is mentioned only in passing within a longer list of topics, code it as other.\n\n**Prompt B**, which produced `llm_reword`:\n\n> Classify each tweet by topic.\n>\n> Answer immigration if the tweet concerns immigration or border policy in any substantial way. Answer other for everything else.\n\nRead them side by side before going on, because the comparison later depends on your judgment that these are two reasonable attempts at one instruction rather than a good prompt and a bad one. Prompt A is longer, gives examples, and states the rule about passing mentions. Prompt B is shorter and leaves \"substantial\" to the model. Either is the sort of thing a researcher writes first, and neither contains an error.\n\nThe script that produced the file is in the repository at `R/w6_generate_llm_labels.R`, and the provenance, including what is and is not reproducible about it, is in `data/llm_labels_w6_README.md`. Read both before the session. The session concerns evaluation, and a measurement whose origin is undocumented cannot be evaluated at all.\n\n### Three label sources, one set of tweets\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhuman <- factor(llm$human, levels = c(\"other\", \"immigration\"))\nllm_main <- factor(llm$llm_main, levels = c(\"other\", \"immigration\"))\n\nconfusionMatrix(nb_pred, human, positive = \"immigration\")$table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Reference\nPrediction    other immigration\n  other          82           5\n  immigration    12          82\n```\n\n\n:::\n\n```{.r .cell-code}\nconfusionMatrix(llm_main, human, positive = \"immigration\")$table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Reference\nPrediction    other immigration\n  other          87           2\n  immigration     7          85\n```\n\n\n:::\n\n```{.r .cell-code}\nround(rbind(\n  naive_bayes = confusionMatrix(nb_pred, human,\n                                positive = \"immigration\")$byClass[c(\"Precision\", \"Recall\")],\n  llm         = confusionMatrix(llm_main, human,\n                                positive = \"immigration\")$byClass[c(\"Precision\", \"Recall\")]\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Precision Recall\nnaive_bayes     0.872  0.943\nllm             0.924  0.977\n```\n\n\n:::\n:::\n\n\nThe language model outperforms the classifier, and it does so having been shown no training data at all. The result is real and should be taken seriously, since it is close to what the published literature reports.\n\nHowever, the shape of the model's errors tells us more than the headline figure does. Recall is much higher than precision, which means the model rarely misses an immigration tweet and fairly regularly flags one the coder did not. Rather than theorize about why, we can read the mistakes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrong <- llm[llm$human != llm$llm_main, c(\"text\", \"human\", \"llm_main\")]\n\nnrow(wrong)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code}\nfalse_alarms <- wrong[wrong$human == \"other\", ]\n\nfor (i in 1:nrow(false_alarms)) {\n  cat(\"-\", substr(false_alarms$text[i], 1, 190), \"\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- ....Kevin is strong on Securing the Border, #USMCA, protecting our #2A, and Loves our Vets and Military. Kevin is a true friend, and has my Complete and Total Endorsement! \n\n- MISSISSIPPI! There is a VERY important election for Governor on November 5th. I need you to get out and VOTE for our Great Republican nominee, @TateReeves. Tate is Strong on Crime, tough on  \n\n- Senator Cindy Hyde-Smith is doing a GREAT JOB for the people of Mississippi and fully supports our #MAGA Agenda. Cindy is tough on Crime, Strong on the Border and Illegal Immigration.... \n\n- I will be signing our 738 Billion Dollar Defense Spending Bill today. It will include 12 weeks  Paid Parental Leave, gives our troops a raise, importantly creates the SPACE FORCE, SOUTHERN B \n\n- ..that this Administration has done. They don’t talk about the great economy, the big tax and regulation cuts, the rebuilding of the Military, “Choice” at our VA, our Vets, Judges and Suprem \n\n- Looking forward to being in the North Carolina tomorrow night. We’re having a BIG RALLY for a great guy, Dan Bishop. Strong on Crime, Borders, your Military and our Vets, we need Dan Bishop  \n\n- I will be interviewed by Jeanine Pirro at 9:00 P.M. on @FoxNews. Watch @JesseBWatters before and @greggutfeld after. All terrific people. I am in the White House waiting for Cryin’ Chuck and \n```\n\n\n:::\n:::\n\n\nSix of these seven are the same kind of tweet. They are campaign endorsements and lists of accomplishments, in which the border appears as one item in a series: strong on crime, strong on the border, protects the Second Amendment, loves our veterans. The defense spending bill tweet is the purest case, since \"SOUTHERN BORDER WALL FUNDING\" sits in a list alongside parental leave, a troop pay raise, the Space Force, and the smoking age.\n\nNow recall where those tweets got their labels. The Week 4 codebook has a rule for exactly this situation: a passing mention inside a longer list is coded `other`. A second rule covers endorsement boilerplate, on the grounds that the border in such a tweet occupies one slot in a formula rather than serving as its subject. Those rules were written by one person, in an afternoon, to resolve cases the original scheme had not anticipated.\n\nSo the model is not misreading English. It is reading these tweets much as you or I would, noticing that immigration is mentioned, and failing to apply a convention that a human coder invented and wrote down somewhere the model never saw. Its errors concentrate almost entirely on the cases where the codebook had to make a judgment call.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissed <- wrong[wrong$human == \"immigration\", ]\n\nfor (i in 1:nrow(missed)) {\n  cat(\"-\", substr(missed$text[i], 1, 190), \"\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- So now the Obama appointed judge on the Census case (Are you a Citizen of the United States?) won’t let the Justice Department use the lawyers  that it wants to use. Could this be a first? \n\n- ....This will supersede USMCA. Likewise I am looking at an economic penalty for the 500 Billion Dollars in illegal DRUGS that are shipped and smuggled through Mexico and across our Southern  \n```\n\n\n:::\n:::\n\n\nThe two it missed point the same way. One concerns the census citizenship question, which the codebook counts as immigration and which a reasonable person might not. The other is about drugs smuggled across the southern border, where the codebook says that drugs count only when the tweet ties them to immigrants or the border, and this tweet arguably does. Neither is a stupid mistake, and both are disagreements about a rule rather than about the tweet.\n\nKeep this in mind for Part III, because the whole session turns on it. Our 95 percent is not a measure of how well the model understands immigration. It is a measure of how often it happens to apply the same conventions as one human coder, and the five percent where it fails is made almost entirely of the places where those conventions were contestable.\n\nOne further asymmetry between the two systems is worth drawing out, since it did not appear in the table. The classifier produced a ROC curve in Part I because it reports a probability, so a threshold can be moved through it and a whole family of classifiers obtained from one fit. The language model reports a label and nothing else. **It is therefore a single point in that space rather than a curve**, with one sensitivity and one specificity, and no dial to turn. Whatever trade-off between precision and recall it happens to embody was fixed by the prompt and the model, and if it over-flags, as this one does, the only instruments available are rewriting the prompt or asking the model for a probability and hoping it means something. The classifier gives you a worse result and more control over it.\n\n### Four ways to shake a measurement\n\nWhat we have so far is one measurement, taken once, by one model, under one prompt. It agreed with the coder 95 percent of the time. Before that number can be believed, it is worth asking whether it would survive the kinds of variation that any real research project will inflict on it without meaning to.\n\nFour questions do that, and they are arranged so that each holds more fixed than the last. The first asks whether the model's claims survive being checked against the world. The second changes the wording of the instruction. The third changes the model. The fourth changes nothing at all. If a measurement cannot survive the fourth, the earlier three were never the problem.\n\n### Check one, the existence check: does the claim survive looking up?\n\nThis check applies whenever a model asserts something that could in principle be looked up. Ask it for a source, then verify that the source exists and says what the model says it says.\n\nNothing in the file above bears on this, since it is not a classification problem, which makes it a workshop exercise rather than a chunk here. Use something you can actually check, and Fearon and Laitin's 2003 article serves well, since it is on the Week 3 reading list and already in your possession:\n\n> Ask the model what Fearon and Laitin found about the relationship between ethnic diversity and civil war onset, and then ask it for the page on which they report it. Open the article and look.\n\nThen do the same with an article you know well from another course, and then with one you have only heard of. The third is the interesting case, because it is the one where you would have believed the answer.\n\nWhat you are looking for is not an error of the ordinary kind. It is a reference with a plausible author, a plausible journal, a plausible year, and a page number, for an article that does not exist, or a real article that says something else. The output gives you nothing to go on, since a fabricated citation is written in exactly the same confident register as a correct one.\n\nThe point is larger than the trick. In Part II we treated the model's labels as data, and the only reason we could trust them at all is that we had 181 human judgments to check them against. The moment a model asserts something you cannot check, you are relying on fluency as a proxy for accuracy, and these are separate properties of a text. Only one of them is visible without leaving the page.\n\n### Check two, prompt stability: does the answer survive a reworded prompt?\n\nThe existence check concerns what a model asserts. The remaining three concern whether a measurement holds still, and the first thing to vary is the one a researcher varies most casually: the wording of the instruction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nllm_reword <- factor(llm$llm_reword, levels = c(\"other\", \"immigration\"))\n\ntable(as_written = llm_main, reworded = llm_reword)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             reworded\nas_written    other immigration\n  other          82           7\n  immigration     0          92\n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(llm_main == llm_reword), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.961\n```\n\n\n:::\n:::\n\n\nPrompt A and prompt B are both defensible, as you saw above, and the model is identical in the two runs. The only thing that changed between them is the wording of the instruction. Yet a share of the corpus is labeled differently depending on which was used, and the identity of those tweets is more instructive than their number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoved <- llm[llm$llm_main != llm$llm_reword, ]\n\nfor (i in 1:nrow(moved)) {\n  cat(\"-\", substr(moved$text[i], 1, 170), \"\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- ....energy independence, manufacturing resilience, illegal immigration coming down, the Wall going up, China confronted, the caliphate defeated, NAFTA renegotiated, our m \n\n- So now the Obama appointed judge on the Census case (Are you a Citizen of the United States?) won’t let the Justice Department use the lawyers  that it wants to use. Coul \n\n- ....This will supersede USMCA. Likewise I am looking at an economic penalty for the 500 Billion Dollars in illegal DRUGS that are shipped and smuggled through Mexico and  \n\n- All necessary work has been completed to declare Mexican Cartels terrorist organizations. Statutorily we are ready to do so. However, at the request of a man who I like a \n\n- “Poll shows Dems losing interest in Impeachment inquiry all across the board. These Polls are actually devastating to the Democrats. But the writing was on the wall. He’s \n\n- It was a very bad week for the Democrats, with the GREAT economic numbers, The Virginia disaster and the State of the Union address. Now, with the terrible offers being m \n\n- The White House will be hosting a very big and very important Social Media Summit today. Would I have become President without Social Media? Yes (probably)! At its conclu \n```\n\n\n:::\n:::\n\n\nThese are the same families of tweet as the errors above. There is the long list of accomplishments with \"illegal immigration coming down\" buried in it, the census citizenship question again, the drug smuggling tweet again, and a poll quotation that mentions building the wall in passing. The tweets that move when the prompt moves are the tweets that were ambiguous under the codebook in the first place.\n\nThat is reassuring and alarming in about equal measure. Reassuring, because the instability is not random: the model wavers exactly where a careful human coder had to stop and make a decision. Alarming, because those borderline cases are frequently the substantively interesting ones, and because a researcher who ran only one prompt would never learn that an eighth of the ambiguous cases could have gone the other way.\n\nSet that share against the error rate from the previous section. The model disagrees with the human coder on about five percent of tweets, and it disagrees with itself under rewording on about four percent. The instability introduced by a reasonable change of wording is therefore nearly as large as the measured error, which means that a paper reporting the accuracy of such a classifier without reporting its sensitivity to the prompt has reported roughly half of what the reader needs.\n\n### Check three, inter-model reliability: does a second model agree?\n\nHere the wording is held fixed and the model changes. Two models were used, and the difference between them matters for how much the comparison is worth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nllm_model2 <- factor(llm$llm_model2, levels = c(\"other\", \"immigration\"))\n\ntable(prompt_A_model_1 = llm_main, prompt_A_model_2 = llm_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                prompt_A_model_2\nprompt_A_model_1 other immigration\n     other          83           6\n     immigration     1          91\n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(llm_main == llm_model2), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.961\n```\n\n\n:::\n:::\n\n\nThat is a second model from the **same company**, which is a weak kind of independence. Two models built by one firm, trained in similar ways on similar text, are closer to two readings from one instrument than to two instruments. If they share an assumption about what the word \"border\" implies, they will agree because of it rather than despite it.\n\nSo we ran prompt A a third time, through a model from a **different company**. The same `ellmer` code does this; only the function changes, from `chat_openai()` to `chat_anthropic()`, which is the practical argument for using a package that is not tied to one provider.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl_c <- paste0(\"https://raw.githubusercontent.com/babakrezaee/\",\n                \"AppliedAI-PoliSci/refs/heads/main/data/\",\n                \"llm_claude_w6.csv\")\n\nclaude <- read.csv(url_c, stringsAsFactors = FALSE,\n                   colClasses = c(id = \"character\"))\n\nllm_claude <- factor(claude$llm_claude, levels = c(\"other\", \"immigration\"))\n\nround(c(same_company  = mean(llm_main == llm_model2),\n        other_company = mean(llm_main == llm_claude)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n same_company other_company \n        0.961         0.950 \n```\n\n\n:::\n:::\n\n\nThe expectation was that agreement across companies would be clearly lower. It is lower, and by two tweets out of 181, which is nothing. We looked for the effect, did not find it at this sample size, and are reporting that rather than quietly dropping the comparison, which is the practice this session is supposed to be teaching.\n\nA more useful question is what happens when all three agree.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunanimous <- llm_main == llm_model2 & llm_main == llm_claude\n\nsum(unanimous)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 169\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(all_three_said = llm_main[unanimous], human = human[unanimous])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              human\nall_three_said other immigration\n   other          81           0\n   immigration     3          85\n```\n\n\n:::\n:::\n\n\nThe three models give the identical label on 169 of the 181 tweets. On those 169, they match the human coder 166 times. **Three systems, two companies, in unanimous agreement, and still wrong three times.**\n\nThose three tweets are the point of the next section. No amount of agreement among models would have found them. The only thing that did was a person who had read the tweet.\n\n### Check four, intra-model reliability: does the same model agree with itself?\n\nThis is the simplest of the four, and the most unsettling. The three before it changed something: the wording, or the model. This one changes nothing at all. Run the identical prompt, on the identical model, a second time, and see whether the answers match. If check three asks whether a different model agrees, check four asks whether the same model agrees with itself.\n\nIt does not. Run twice over these 181 tweets, the model disagreed with itself on **8 of them**, and the accuracy against the hand labels moved from 95.0 percent on one run to 93.9 percent on another. Nothing was altered between the runs. The question was the same, the model was the same, and the number you would have written in your paper depends on which afternoon you ran it.\n\nFive of those eight tweets are the same ones that flip when the prompt is reworded. Counting everything that moved under any of the three perturbations, rewording, changing model, or simply asking again, the total is 12 tweets out of 181. The model is immovable on about 93 percent of the corpus and close to flipping a coin on the rest, and that unstable remainder is the same set of borderline cases the Week 4 codebook needed its tie-break rules for. The checks were not measuring three different things. They were finding the same ambiguous tweets by three different routes.\n\n### Why that happens, and why we could not switch it off\n\nWeek 5's first diagram showed the model producing a probability for every possible next token, and something then choosing one. **Temperature** is the dial on that choice.\n\nAt a temperature of zero the model always takes the most likely token. The same question gives the same answer every time, which is dull for writing and exactly what you want for measurement. Turn the dial up and the choice becomes a draw rather than a maximum, so less likely tokens become reachable, the output is more varied, and repeated calls stop agreeing. For years the standard advice to anybody using these models as a research instrument was therefore simple: set the temperature to zero and report that you did.\n\nThat advice no longer works here, and the reason is worth understanding.\n\nThe model we are using is a **reasoning model**. Rather than answering immediately it first generates a chain of intermediate steps, working through the problem before committing, and only then produces the answer. That internal process was built and tuned at one particular setting of the dial. Turning the dial down would not make such a model more reliable; it would interfere with the very process the model was trained to carry out, and the provider has judged that the result would be worse rather than more repeatable. So the setting is locked.\n\nIt is locked firmly. We asked for a temperature of zero on all 181 tweets and every single call was refused, with the API replying that only the default value is supported. A setting of 0.5 is refused in the same way. The parameter exists in the R package, it is named in every methods paper on this subject, and on this model you may not use it.\n\nSit with the consequence rather than the inconvenience. The standard remedy for non-determinism is unavailable, not because of a limitation of the method but because a company decided that you should not have it, for reasons that are probably sound and that you are in no position to evaluate. You can still report the instability, which is what the eight tweets above do. You cannot remove it.\n\n### Agreement is not accuracy\n\nSeveral agreement rates have now been produced, and the temptation is to read them as so many measurements of the same thing. They are not, and the distinction is the most important idea in this part.\n\nAgreement between two prompts, between two models, between two companies, or between two runs of the same model establishes that a measurement is **reproducible**. It says that the number would come out much the same if somebody else ran it, which is a real property and not a trivial one. However, it says nothing whatever about whether the number is **right**. Models trained on overlapping corpora, with overlapping assumptions about what the word \"border\" implies, may agree with one another precisely because they share a bias, and their agreement is then evidence of a common error rather than of a correct answer. Check three showed exactly that, three times over.\n\nOnly the human labels speak to accuracy. Thus the comparison that matters is the first one, against `human`, and the reliability checks are supporting evidence rather than substitutes.\n\nThat said, the human labels are themselves a measurement rather than the truth. They were produced by one coder applying one written codebook, and the Week 4 documentation records the four rules invented to resolve cases the scheme did not anticipate. A second coder would place some tweets differently. The honest statement of the result is therefore not that the model is 95 percent accurate, but that it agrees 95 percent of the time with one person's application of one coding scheme to 181 tweets. Every further claim rests on that sentence, and it is a good deal weaker than the number alone suggests. On the practice of treating human judgment as the benchmark, and on what that requires, see Lowe and Benoit [@lowe2013].\n\nPart II has established how far the number can be trusted as a measurement of what the coder did. Part III asks a harder question: whether what the coder did is what we wanted measured, and whether the test was a test at all.\n\n## Part III. Why a good score can be the wrong number\n\n### What the score is a score of\n\nPolitical scientists have a word for the problem this section is about, and it is one of the few places in this course where the discipline is ahead of computer science rather than behind it. **Construct validity** asks whether an instrument measures the concept it claims to measure, as distinct from measuring something close to it, something correlated with it, or something merely easier to count.\n\nThe number in Part II is an agreement rate against a codebook. Whether it is also a measure of the aboutness of immigration depends entirely on whether the codebook captured that concept, and that codebook was the work of a single coder resolving awkward cases as they arose. Rule one of it, which sends a tweet listing ten accomplishments with \"Border\" seventh into the `other` category, is a judgment call that a different coder could defensibly reverse. Reverse it, and the labels change, and the model's accuracy against the new labels changes, and nothing about the model or the tweets has moved at all.\n\nFour questions bear on any evaluation, and they are not one question asked four times. Each one can be put to our own classifier.\n\n**Does the measure cover the concept, or only part of it?** Our scheme counts a tweet about the census citizenship question as immigration and a tweet endorsing a candidate who is \"strong on the border\" as not. A reader who thinks immigration politics is substantially about how politicians signal toughness on it would say we have measured the policy debate and discarded the political performance, which for many research questions is the half that matters.\n\n**Does it agree with an established measure of the same thing?** The Comparative Agendas Project and the Manifesto Project have both coded political text for immigration content for years, using schemes refined over decades by multiple coders. Ours was the work of one person over a few hours. We never checked our labels against either, and we could have.\n\n**Does the measure behave as the concept should behave?** Here we do reasonably well. The immigration share falls sharply after the first half of 2019, which is what anybody following the shutdown and then impeachment would expect, and a measure that showed no such movement would be suspect regardless of its agreement rate.\n\n**What follows from using it?** Suppose this classifier were not a teaching exercise but a monitoring system, and suppose politicians learned which words triggered it. The endorsement tweets in Part II show that the border can be invoked while saying nothing about it, and a measure deployed at scale eventually changes the behavior of whoever is being measured.\n\nAn evaluation that answers only the question \"how often does it agree with my labels\" has addressed the first of these badly and the other three not at all.\n\n### When the test was not really a test\n\nA score can also be too high for a reason that has nothing to do with the concept. It can be too high because the test was not a test.\n\nThe idea is the same one that makes an exam meaningful. An exam measures what a student knows only if the student has not seen the questions beforehand. Show them the paper during revision and they will score well, the marking will be correct, the arithmetic will be sound, and the number will mean nothing about what they would do on an exam they had not seen.\n\nThe same thing happens to models, and it has a name. **Leakage** is any way in which information from the test set reaches the model before it is tested. It does not require cheating or carelessness. It usually happens through a decision that looks like housekeeping.\n\nWe can produce it deliberately, in one line, and watch it work. The first route runs through the vocabulary.\n\nPart I built the classifier's vocabulary from the training tweets only. Here is that line again, beside the version that forgets to do so.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What Part I did: look only at the 724 training tweets, and keep every word\n# used at least 5 times among them.\nlength(freq_words)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 651\n```\n\n\n:::\n\n```{.r .cell-code}\n# The careless version: look at all 905 tweets, including the 181 that are\n# about to be used as the test set.\nfreq_leaky <- findFreqTerms(dtm, 5)\n\nlength(freq_leaky)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 749\n```\n\n\n:::\n:::\n\n\n`dtm` is the full matrix of 905 tweets. `dtm[train_id, ]` is just the 724 training rows, which is what Part I passed to `findFreqTerms()`. Dropping that `[train_id, ]` is the whole mistake, and it is one keystroke.\n\nThe careless vocabulary is larger, by around a hundred words. Those extra words are the interesting part, and `setdiff()` isolates them: it returns the items in the first set that are not in the second.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(setdiff(freq_leaky, freq_words), 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"account\"     \"addit\"       \"address\"     \"amaz\"        \"appoint\"    \n [6] \"apprentic\"   \"assist\"      \"associ\"      \"benefit\"     \"biden\"      \n[11] \"bishop\"      \"black\"       \"bless\"       \"brought\"     \"captur\"     \n[16] \"center\"      \"condit\"      \"congression\" \"consider\"    \"convers\"    \n```\n\n\n:::\n:::\n\n\nEach of these is a word that was not frequent enough among the training tweets to qualify, and became frequent enough only once the test tweets were counted. They are in the model's vocabulary because of documents it is about to be graded on. Every one of them is now a feature the classifier can use, and the classifier has been told something about its own exam.\n\nThe second route is easier to take, and we took it in Part I. It runs through a choice rather than through a line of code.\n\nThat threshold table reported precision, recall, and accuracy at nine cut points, all computed on the test set. Nothing is wrong with looking. The question is what happens if you then pick.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The row of the sweep where accuracy happens to be highest.\n# which.max() returns the position of the largest value in a vector.\nbest <- sweep_out[which.max(sweep_out$accuracy), ]\n\n# sweep_out$default is the TRUE/FALSE column marking the 0.5 row, so this\n# compares the accuracy at the default against the best available anywhere.\nround(c(at_the_default = sweep_out$accuracy[sweep_out$default],\n        best_on_test   = best$accuracy), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nat_the_default   best_on_test \n         0.906          0.923 \n```\n\n\n:::\n\n```{.r .cell-code}\nbest$threshold\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6\n```\n\n\n:::\n:::\n\n\nThe best threshold is not 0.5, and it delivers a visibly higher accuracy, worth a few more tweets correct. We could report that number. It came out of real code, run on real data, with no mistake anywhere in it.\n\nIt would still be false as a statement about new tweets, because the threshold was chosen by looking at the answers. We did not estimate which cut point works; we looked up which cut point happened to work here. On the next 181 tweets it would not be the best, and the figure we reported would not be reproduced.\n\nNotice what this episode did not include. No error message, no warning, no suspicious output, and no moment at which anybody did anything that felt wrong. **Leakage does not announce itself as a bug. It announces itself as a better result.** That is why it survives peer review.\n\n### The version you cannot check\n\nBoth examples above are repairable. Pass `dtm[train_id, ]`, choose the threshold on data the model has not been judged on, and the problem goes away.\n\nNow the same problem in a form where nothing can be done. **Contamination** is leakage into a model you did not train: the possibility that your test documents were part of the training data of the model you are testing. With a commercial language model, whose training corpus is undisclosed, the honest position is not that this did not happen. It is that you cannot know.\n\nOur own case is not hypothetical. These are tweets by a sitting president, quoted in thousands of news articles, analysed in academic papers, and archived in at least three public GitHub repositories, including the one this corpus was built from. If any text on the internet was in that training data, this text was. The model may well have met these exact tweets before, accompanied by journalism explaining what each was about, which is considerably more than the paragraph of instruction we gave it.\n\nThis cannot be checked by us or by anyone outside the company, and it is not a reason to abandon the method. It is a reason to write the limitation down rather than report 95 percent as though it were a clean out-of-sample result.\n\nIt also unsettles the comparison in Part II. The Naive Bayes classifier saw 724 tweets and nothing else in its entire existence. The language model may have seen these tweets and the commentary about them. The contest was never as fair as the table made it look, and the fairer reading of Part II is that a system with an unknown and probably large advantage beat one with none.\n\n### What a benchmark number means\n\nPublished evaluations of these systems are mostly benchmark scores, and three pathologies recur often enough to be recognizable. Two of them we have already committed in this handout, which is the quickest way to understand them.\n\nBenchmarks **saturate**. Once a test is widely used, systems are built and selected against it until the leading ones all score within a point or two of each other and of the ceiling, at which stage the test has stopped ranking the systems and started ranking the noise. The remedy is a harder test, so the cycle runs again, and the published scores across a few years of such cycles are not comparable with one another.\n\nBenchmarks are **gamed**, though rarely by fraud. The ordinary mechanism is the one from the previous section: we swept a threshold across our test set and could have reported the best value we found. Nobody lied, no rule was broken, and the reported figure would still have described our test set rather than the world. Scale that up to an industry in which benchmark position determines funding and procurement, and the pressure runs the same way without anybody deciding that it should.\n\nAnd a growing share of evaluation now uses one language model to **judge** the output of another, since human raters are slow and expensive. This is efficient and it is circular, for the reason Part II gave: a judge trained on much the same text as the system it grades will share its assumptions about what a good answer looks like, so agreement between them is weak evidence of quality. We saw the small version of this in check three: three models agreed unanimously on 169 tweets and were wrong on three of them, and nothing about their agreement revealed which three.\n\nThe practical conclusion is narrow, and it is the one thing from this section to carry out of the room. When a procurement document, a vendor, or a paper reports that a system is 94 percent accurate, the figure is a claim about performance on some benchmark, and the questions that matter are which one, constructed by whom, measured when, and against whose labels. None of those is a technical question, and a political scientist is as well placed to ask them as anybody.\n\n## Part IV. When the measurement feeds a regression\n\nEverything so far has treated the labels as the end product. In a research project they almost never are. The labels become a variable, the variable enters an analysis, and the analysis produces the number that appears in the abstract.\n\nTake a question we can actually ask of these 181 tweets. Immigration dominated the first part of 2019, through the shutdown over wall funding and the national emergency declaration, and receded later in the year as impeachment took over. How much larger was the immigration share in the first half of the year than in the second?\n\nSplit the test tweets by half of the year, compute the immigration share in each half, and take the difference. Do it three times, once with each set of labels. The hand labels put the gap at roughly 36 percentage points. The model's labels put it at roughly 30, and the reworded prompt at roughly 27. A classifier that is right 95 percent of the time has understated a substantively central quantity by something between a sixth and a quarter.\n\nThe mechanism is general, and worth following through once. The model over-flags, as Part II established, so it adds spurious immigration tweets in both halves of the year. In the second half, where genuine immigration tweets are scarce, those additions are a much larger share of the total. The second-half figure is therefore inflated more than the first-half figure, the gap between them narrows, and the result is pulled toward zero.\n\nTwo things make this worse than ordinary measurement error. It does not shrink as the sample grows, because it is bias and not noise, so a bigger corpus labeled the same way buys a more precise estimate of the wrong number. And nothing in the output signals any of it: the analysis runs, the standard errors look ordinary, and the table is publishable. Egami and colleagues [@egami2023] show this formally, finding that labels of 80 to 90 percent accuracy produce substantial bias downstream. Our 95 percent sits above the range they examine, and the attenuation is plainly visible anyway.\n\n### What to do about it\n\nTheir correction needs more statistics than this course carries. The practice that makes any correction possible does not, and it is why your Type B projects were told to hand-code a validation sample.\n\nHand-code a random sample of your corpus before you look at what the model produced. Report the agreement rate, and report what the disagreements look like rather than only how many there are, because a systematic direction of error is far more damaging than a symmetric one. Then state your substantive result alongside the quality of the labels it rests on. A reader can discount an estimate from imperfect labels when told how imperfect they are. A reader can do nothing at all with an estimate whose labels are undescribed.\n\nThose four parts have all assumed that the evaluation can actually be carried out. The last section asks who is in a position to carry one out at all.\n\n## The politics of who may audit\n\nEverything in this session has been possible because we hold the labels, the corpus, the code, and the output. That is an unusual position, and very little of it generalizes.\n\nA researcher wishing to evaluate a deployed system almost never has any of those things. The training data is undisclosed, so contamination cannot be checked. The weights are inaccessible, so the system can be probed only from outside, one query at a time, under terms of service that frequently prohibit exactly the systematic probing an audit requires. The model can be changed or withdrawn between the measurement and its publication. And the organization with the most complete access to the system is the one with the strongest interest in the answer.\n\nFor these reasons the question of who may audit has become a regulatory one rather than a technical one, and proposals for legal safe harbor, protecting good-faith independent evaluation from liability, are now a live issue. Black-box access is not sufficient for a rigorous audit, and arranging for something better is a matter of law and institutional design.\n\nWeek 2 asked who defines similarity, Week 3 who sets the threshold, Week 4 who writes the codebook, and Week 5 who owns the classifier. The question here is narrower and harder. **Who is allowed to check?** By the time a system is deployed at scale, the answer is usually settled, and it is usually settled in favor of the party being evaluated.\n\n## Reading\n\nGrimmer, J., and Stewart, B. M. 2013. \"Text as Data: The Promise and Pitfalls of Automatic Content Analysis Methods for Political Texts.\" *Political Analysis* 21(3): 267--297. [@grimmer2013]\n\nAssigned in Week 4 and returned to here for its central claim, that validation is not optional and cannot be replaced by a well-chosen metric. Read their discussion of validation against what we did in Part II, and ask which of their recommendations our procedure actually satisfies.\n\nLowe, W., and Benoit, K. 2013. \"Validating Estimates of Latent Traits from Textual Data Using Human Judgment as a Benchmark.\" *Political Analysis* 21(3): 298--313. [@lowe2013]\n\nPublished immediately after Grimmer and Stewart in the same issue, and the more useful of the two for this week. Their subject is precisely the move we made in Part II, treating human coders as the standard against which an automated measure is judged, and their contribution is to take seriously that human judgment is itself variable and must be modeled rather than assumed.\n\nEgami, N., Hinck, M., Stewart, B. M., and Wei, H. 2023. \"Using Imperfect Surrogates for Downstream Inference: Design-Based Supervised Learning for Social Science Applications of Large Language Models.\" *Advances in Neural Information Processing Systems* 36. [@egami2023]\n\nThe source of Part IV. The paper is technical and the estimator is beyond us, but the demonstration in its opening pages is not, and it is the single most important thing in this week's reading for anybody whose project will use model-generated labels. Read it for the result rather than the proof.\n\n## Before the workshop\n\nRun the whole handout once. Nothing in it makes an API call, so it needs no key and no credit, and the only new package is `pROC`.\n\nRead `data/llm_labels_w6_README.md` in the course repository, particularly the section on what prevents exact reproduction. Assignment 3 assumes you have.\n\nBring one factual question in your own area of interest, specific enough that a wrong answer would be recognizable to you. You will need it for the existence check.\n\n## Questions for the session\n\nCome with a view on at least two of these.\n\n1. The language model beat a classifier trained on 724 hand-labeled examples, having seen none. Give the strongest argument you can that Week 4 was nonetheless worth doing, and then give the strongest argument against yourself.\n\n2. Two prompts, each of which a competent researcher might have written first, label about four percent of the corpus differently. What should a journal require an author to report about this, and what would it cost the author to comply?\n\n3. Part II insisted that agreement between two models is not evidence of accuracy. Construct a case in which two independent models agree closely and are both substantially wrong, and say what you would need in order to detect it.\n\n4. Our accuracy figure measures agreement with one coder's application of one codebook. Suppose a second coder had labeled the same tweets and agreed with the first on 90 percent of them. What is the most the model's 95 percent can now mean?\n\n5. The attenuation in Part IV went in a predictable direction once the mechanism was understood. Describe a research question where the same kind of error would bias an estimate *upward* instead, and explain why.\n\n6. You are advising a ministry considering a system that its vendor reports as 94 percent accurate. List, in order, the questions you would ask before the contract is signed, and mark which of them the vendor is likely to refuse to answer.",
    "supporting": [
      "w06-evaluation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script type=\"ojs-define\">\n{\"contents\":[{\"name\":\"eval_data\",\"value\":{\"prob\":[1.65067941367212e-09,0.0077542722997739,0.988166614500447,0.162157129713285,0.808173997771735,0.00211881155785183,0.989616671390707,0.000294095549644884,0.473783645537702,0.287883519964915,0.997644899722551,0.999989720548562,0.00198788519729145,0.99841386138878,0.99875722384042,0.998243812795357,0.550333614268675,0.999999998996383,0.962700111912642,0.999999996450532,0.000101594321047599,0.876013704442317,0.000150501018485832,0.999456425299027,1.11226887749723e-05,0.00291594511891455,0.053487983446013,0.000419518842208348,0.999999998101543,2.26704883147525e-05,0.000480288479329989,0.999999999980779,0.99998522666742,4.56095974986426e-09,0.975200341347834,0.024124632514067,0.814958395960909,0.0075551720718102,0.363722909308297,0.999999996193201,0.0005171863723368,0.999999992148926,0.435860265331016,0.00639900997015548,6.16571143284966e-06,7.30481833057897e-07,0.000383450700395031,0.999999999555687,0.000298163300481971,0.57031593520558,0.0115495932866935,0.00575619721134626,8.61358679810278e-10,0.999966452146775,0.997561304869217,0.0079428517811857,6.16745893748984e-06,0.998888438964454,0.972106778080016,3.42379158927674e-05,7.79867969498728e-05,0.162649249788546,0.0569097601767724,0.999917789220055,1.29697811503272e-05,0.999304474498107,0.814641991253713,3.60518232748998e-07,0.5535431162062,0.935134398975932,0.916879376760851,0.999993207941486,0.0849983561595112,0.997464698521932,0.999989998023639,0.188233392883671,0.984055947325459,0.0161626668052737,0.999999777390762,0.999426466017191,0.93093514065614,9.36075404863637e-07,0.997950593546467,0.087039568172249,0.99870185242002,0.000196942561083478,0.960228894323958,0.00397965975934109,0.000566685287427916,2.31803620964815e-09,0.000137382553531073,0.731212671058436,0.980714843381193,0.00441409829941659,0.986650827698514,0.0758762044099592,0.930553277617029,0.979314854878882,0.999782224154651,0.691580148766304,2.74766876804454e-05,6.21304137380096e-07,0.999860647405063,0.0047712072902945,0.997073871825486,0.999719043283969,0.799105424590154,0.00109955894745737,0.00422686899660541,0.00211597836602574,0.995550038280075,0.00393206657703497,0.999999998977038,0.00350309918916737,0.00558545134191299,0.00249723729036247,0.999990174989352,0.99707751487405,0.999999772010814,0.00849894326118493,0.999935236441369,0.978302245197769,0.0495359229773372,0.999206568834794,1.3087236202759e-06,0.166069899444063,0.000227017106175336,0.0141574953555704,0.0799838543550997,0.968793535786277,0.999572627300863,0.350334666214966,7.15051415765031e-05,0.19571880505641,1.53027362257554e-05,0.989482075279449,0.999999825516638,9.33072007034355e-05,0.995510368693202,0.942591254650638,0.999975119721753,6.9712600944926e-06,0.998969413224354,0.963718676437198,0.998394257638951,0.99493396440412,0.00114941318817813,2.99274007121129e-05,5.60448877641851e-09,0.998927766917776,0.000677111528116183,1.0533408997741e-06,5.18603020325898e-07,0.185014493714789,0.977201827080075,0.996845454456124,0.0299474660528033,0.999999996009686,0.322262440570745,7.77891342923366e-08,0.999662443923179,0.999998617885936,0.999999974693357,0.999946650794291,0.0260972468080726,0.999998921329029,0.994234550734993,0.776991785304651,0.00118040313227636,0.999999263335311,0.0799838543550997,0.925859999605776,0.999206568834794,0.000141124232865118,0.712871848902082,0.999999900740333,0.880566309713744,0.999998563768809,0.99992618435843,0.999999999999943,0.999962573195801],\"truth\":[\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"other\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"immigration\",\"other\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"other\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"immigration\",\"other\",\"other\",\"other\",\"other\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"other\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"other\",\"other\",\"immigration\",\"other\",\"immigration\",\"immigration\",\"immigration\",\"immigration\"]}}]}\n</script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}